# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfacePrincipal.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowPrincipal(object):
    def setupUi(self, MainWindowPrincipal):
        MainWindowPrincipal.setObjectName(_fromUtf8("MainWindowPrincipal"))
        MainWindowPrincipal.setWindowModality(QtCore.Qt.WindowModal)
        MainWindowPrincipal.setEnabled(True)
        MainWindowPrincipal.resize(822, 300)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowPrincipal.sizePolicy().hasHeightForWidth())
        MainWindowPrincipal.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        MainWindowPrincipal.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        MainWindowPrincipal.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/beagle3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowPrincipal.setWindowIcon(icon)
        MainWindowPrincipal.setWindowOpacity(1.0)
        MainWindowPrincipal.setToolTip(_fromUtf8(""))
        MainWindowPrincipal.setAutoFillBackground(False)
        MainWindowPrincipal.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindowPrincipal)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 821, 77))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalLayoutWidget_2.setFont(font)
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.toolButton_gerenciaExperimentos = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        self.toolButton_gerenciaExperimentos.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_gerenciaExperimentos.sizePolicy().hasHeightForWidth())
        self.toolButton_gerenciaExperimentos.setSizePolicy(sizePolicy)
        self.toolButton_gerenciaExperimentos.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_gerenciaExperimentos.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_gerenciaExperimentos.setFont(font)
        self.toolButton_gerenciaExperimentos.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_gerenciaExperimentos.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/gerenciar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_gerenciaExperimentos.setIcon(icon1)
        self.toolButton_gerenciaExperimentos.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_gerenciaExperimentos.setAutoRepeatDelay(300)
        self.toolButton_gerenciaExperimentos.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_gerenciaExperimentos.setAutoRaise(False)
        self.toolButton_gerenciaExperimentos.setObjectName(_fromUtf8("toolButton_gerenciaExperimentos"))
        self.horizontalLayout_2.addWidget(self.toolButton_gerenciaExperimentos)
        self.toolButton_downloadPdb = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_downloadPdb.sizePolicy().hasHeightForWidth())
        self.toolButton_downloadPdb.setSizePolicy(sizePolicy)
        self.toolButton_downloadPdb.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_downloadPdb.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_downloadPdb.setFont(font)
        self.toolButton_downloadPdb.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_downloadPdb.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/novo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_downloadPdb.setIcon(icon2)
        self.toolButton_downloadPdb.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_downloadPdb.setAutoRepeatDelay(300)
        self.toolButton_downloadPdb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_downloadPdb.setAutoRaise(False)
        self.toolButton_downloadPdb.setObjectName(_fromUtf8("toolButton_downloadPdb"))
        self.horizontalLayout_2.addWidget(self.toolButton_downloadPdb)
        self.line_2 = QtGui.QFrame(self.horizontalLayoutWidget_2)
        self.line_2.setLineWidth(3)
        self.line_2.setMidLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.toolButton_geraArquivos = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_geraArquivos.sizePolicy().hasHeightForWidth())
        self.toolButton_geraArquivos.setSizePolicy(sizePolicy)
        self.toolButton_geraArquivos.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_geraArquivos.setMaximumSize(QtCore.QSize(86, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_geraArquivos.setFont(font)
        self.toolButton_geraArquivos.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_geraArquivos.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/engrenagens.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_geraArquivos.setIcon(icon3)
        self.toolButton_geraArquivos.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_geraArquivos.setAutoRepeatDelay(300)
        self.toolButton_geraArquivos.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_geraArquivos.setAutoRaise(False)
        self.toolButton_geraArquivos.setObjectName(_fromUtf8("toolButton_geraArquivos"))
        self.horizontalLayout_2.addWidget(self.toolButton_geraArquivos)
        self.toolButton_regressao = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_regressao.sizePolicy().hasHeightForWidth())
        self.toolButton_regressao.setSizePolicy(sizePolicy)
        self.toolButton_regressao.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_regressao.setMaximumSize(QtCore.QSize(86, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_regressao.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/regresao.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_regressao.setIcon(icon4)
        self.toolButton_regressao.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_regressao.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_regressao.setObjectName(_fromUtf8("toolButton_regressao"))
        self.horizontalLayout_2.addWidget(self.toolButton_regressao)
        self.toolButton_correlacao = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(66)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_correlacao.sizePolicy().hasHeightForWidth())
        self.toolButton_correlacao.setSizePolicy(sizePolicy)
        self.toolButton_correlacao.setMinimumSize(QtCore.QSize(66, 65))
        self.toolButton_correlacao.setMaximumSize(QtCore.QSize(88, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_correlacao.setFont(font)
        self.toolButton_correlacao.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_correlacao.setAutoFillBackground(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/correlacao.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_correlacao.setIcon(icon5)
        self.toolButton_correlacao.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_correlacao.setAutoRepeatDelay(300)
        self.toolButton_correlacao.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_correlacao.setAutoRaise(False)
        self.toolButton_correlacao.setObjectName(_fromUtf8("toolButton_correlacao"))
        self.horizontalLayout_2.addWidget(self.toolButton_correlacao)
        self.toolButton_experimento = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_experimento.sizePolicy().hasHeightForWidth())
        self.toolButton_experimento.setSizePolicy(sizePolicy)
        self.toolButton_experimento.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_experimento.setMaximumSize(QtCore.QSize(86, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_experimento.setFont(font)
        self.toolButton_experimento.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_experimento.setAutoFillBackground(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/experimento.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_experimento.setIcon(icon6)
        self.toolButton_experimento.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_experimento.setAutoRepeatDelay(300)
        self.toolButton_experimento.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_experimento.setAutoRaise(False)
        self.toolButton_experimento.setObjectName(_fromUtf8("toolButton_experimento"))
        self.horizontalLayout_2.addWidget(self.toolButton_experimento)
        self.line_3 = QtGui.QFrame(self.horizontalLayoutWidget_2)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setLineWidth(3)
        self.line_3.setMidLineWidth(2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.toolButton_ajuda = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_ajuda.sizePolicy().hasHeightForWidth())
        self.toolButton_ajuda.setSizePolicy(sizePolicy)
        self.toolButton_ajuda.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_ajuda.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_ajuda.setFont(font)
        self.toolButton_ajuda.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_ajuda.setAutoFillBackground(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/ajuda.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ajuda.setIcon(icon7)
        self.toolButton_ajuda.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_ajuda.setAutoRepeatDelay(300)
        self.toolButton_ajuda.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_ajuda.setAutoRaise(False)
        self.toolButton_ajuda.setObjectName(_fromUtf8("toolButton_ajuda"))
        self.horizontalLayout_2.addWidget(self.toolButton_ajuda)
        self.toolButton_informacoes = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_informacoes.sizePolicy().hasHeightForWidth())
        self.toolButton_informacoes.setSizePolicy(sizePolicy)
        self.toolButton_informacoes.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_informacoes.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_informacoes.setFont(font)
        self.toolButton_informacoes.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_informacoes.setAutoFillBackground(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("img/informacao.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_informacoes.setIcon(icon8)
        self.toolButton_informacoes.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_informacoes.setAutoRepeatDelay(300)
        self.toolButton_informacoes.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_informacoes.setAutoRaise(False)
        self.toolButton_informacoes.setObjectName(_fromUtf8("toolButton_informacoes"))
        self.horizontalLayout_2.addWidget(self.toolButton_informacoes)
        self.toolButton_sair = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.toolButton_sair.sizePolicy().hasHeightForWidth())
        self.toolButton_sair.setSizePolicy(sizePolicy)
        self.toolButton_sair.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_sair.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_sair.setFont(font)
        self.toolButton_sair.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_sair.setAutoFillBackground(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_sair.setIcon(icon9)
        self.toolButton_sair.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_sair.setAutoRepeatDelay(300)
        self.toolButton_sair.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_sair.setAutoRaise(False)
        self.toolButton_sair.setObjectName(_fromUtf8("toolButton_sair"))
        self.horizontalLayout_2.addWidget(self.toolButton_sair)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 71, 822, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(197, 123, 180, 114))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label.setFont(font)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("img/TabaComLetras.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_version = QtGui.QLabel(self.centralwidget)
        self.label_version.setGeometry(QtCore.QRect(709, 226, 111, 10))
        self.label_version.setMinimumSize(QtCore.QSize(60, 10))
        self.label_version.setBaseSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_version.setFont(font)
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setWordWrap(True)
        self.label_version.setOpenExternalLinks(False)
        self.label_version.setObjectName(_fromUtf8("label_version"))
        self.label_Titulo2 = QtGui.QLabel(self.centralwidget)
        self.label_Titulo2.setGeometry(QtCore.QRect(300, 203, 251, 20))
        self.label_Titulo2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Titulo2.setFont(font)
        self.label_Titulo2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Titulo2.setWordWrap(True)
        self.label_Titulo2.setObjectName(_fromUtf8("label_Titulo2"))
        MainWindowPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowPrincipal)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindowPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowPrincipal)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowPrincipal.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindowPrincipal)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindowPrincipal.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionBaixaPdbsProteinas = QtGui.QAction(MainWindowPrincipal)
        self.actionBaixaPdbsProteinas.setObjectName(_fromUtf8("actionBaixaPdbsProteinas"))
        self.actionGeraArquivosMedias = QtGui.QAction(MainWindowPrincipal)
        self.actionGeraArquivosMedias.setObjectName(_fromUtf8("actionGeraArquivosMedias"))
        self.actionGeraArquivosRegressaoLinear = QtGui.QAction(MainWindowPrincipal)
        self.actionGeraArquivosRegressaoLinear.setObjectName(_fromUtf8("actionGeraArquivosRegressaoLinear"))
        self.actionFazRegressaoLinear = QtGui.QAction(MainWindowPrincipal)
        self.actionFazRegressaoLinear.setObjectName(_fromUtf8("actionFazRegressaoLinear"))
        self.actionSair = QtGui.QAction(MainWindowPrincipal)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))

        self.retranslateUi(MainWindowPrincipal)
        QtCore.QObject.connect(self.toolButton_correlacao, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.fazCorrelacao)
        QtCore.QObject.connect(self.toolButton_downloadPdb, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.baixaPdbsProteinas)
        QtCore.QObject.connect(self.toolButton_experimento, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.fazExperimento)
        QtCore.QObject.connect(self.toolButton_geraArquivos, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.geraArquivoParaRegressao)
        QtCore.QObject.connect(self.toolButton_gerenciaExperimentos, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.gerenciarExperimentos)
        QtCore.QObject.connect(self.toolButton_informacoes, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.informacoes)
        QtCore.QObject.connect(self.toolButton_ajuda, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.ajuda)
        QtCore.QObject.connect(self.toolButton_sair, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.deleteLater)
        QtCore.QObject.connect(self.toolButton_sair, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.sair)
        QtCore.QObject.connect(self.toolButton_regressao, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowPrincipal.fazRegressao)
        QtCore.QMetaObject.connectSlotsByName(MainWindowPrincipal)

    def retranslateUi(self, MainWindowPrincipal):
        MainWindowPrincipal.setWindowTitle(_translate("MainWindowPrincipal", "TABA - Binding Affinity", None))
        MainWindowPrincipal.setStatusTip(_translate("MainWindowPrincipal", "Developed by Amauri Duarte and Prof. Dr. Walter F. de Azevedo Jr.", None))
        MainWindowPrincipal.setWhatsThis(_translate("MainWindowPrincipal", "Developed by Amauri Duarte and Prof. Dr. Walter F. de Azevedo Jr.", None))
        MainWindowPrincipal.setAccessibleName(_translate("MainWindowPrincipal", "Binding affinity", None))
        MainWindowPrincipal.setAccessibleDescription(_translate("MainWindowPrincipal", "Developed by Amauri Duarte and Prof. Dr.  Walter F. de Azevedo Jr.", None))
        self.toolButton_gerenciaExperimentos.setToolTip(_translate("MainWindowPrincipal", "Manages experiments", None))
        self.toolButton_gerenciaExperimentos.setStatusTip(_translate("MainWindowPrincipal", "Manages experiments", None))
        self.toolButton_gerenciaExperimentos.setWhatsThis(_translate("MainWindowPrincipal", "Manages experiments", None))
        self.toolButton_gerenciaExperimentos.setAccessibleName(_translate("MainWindowPrincipal", "Download", None))
        self.toolButton_gerenciaExperimentos.setText(_translate("MainWindowPrincipal", "&Manage", None))
        self.toolButton_downloadPdb.setToolTip(_translate("MainWindowPrincipal", "Handle PDB structure", None))
        self.toolButton_downloadPdb.setStatusTip(_translate("MainWindowPrincipal", "Handle PDB structure", None))
        self.toolButton_downloadPdb.setWhatsThis(_translate("MainWindowPrincipal", "Handle PDB structure", None))
        self.toolButton_downloadPdb.setAccessibleName(_translate("MainWindowPrincipal", "Handle PDB structure", None))
        self.toolButton_downloadPdb.setText(_translate("MainWindowPrincipal", "&PDB", None))
        self.toolButton_geraArquivos.setToolTip(_translate("MainWindowPrincipal", "Generate files to linear regression", None))
        self.toolButton_geraArquivos.setStatusTip(_translate("MainWindowPrincipal", "Generate files to regression", None))
        self.toolButton_geraArquivos.setWhatsThis(_translate("MainWindowPrincipal", "Generate files to regression", None))
        self.toolButton_geraArquivos.setAccessibleName(_translate("MainWindowPrincipal", "Download", None))
        self.toolButton_geraArquivos.setText(_translate("MainWindowPrincipal", "Make &Files", None))
        self.toolButton_regressao.setToolTip(_translate("MainWindowPrincipal", "Do linear regression", None))
        self.toolButton_regressao.setStatusTip(_translate("MainWindowPrincipal", "Do linear regression", None))
        self.toolButton_regressao.setText(_translate("MainWindowPrincipal", "&Regression", None))
        self.toolButton_correlacao.setToolTip(_translate("MainWindowPrincipal", "Do Correlation", None))
        self.toolButton_correlacao.setStatusTip(_translate("MainWindowPrincipal", "Do Correlation", None))
        self.toolButton_correlacao.setWhatsThis(_translate("MainWindowPrincipal", "Do Correlation", None))
        self.toolButton_correlacao.setAccessibleName(_translate("MainWindowPrincipal", "Correlation", None))
        self.toolButton_correlacao.setText(_translate("MainWindowPrincipal", "&Corrrelation", None))
        self.toolButton_experimento.setToolTip(_translate("MainWindowPrincipal", "User experiment", None))
        self.toolButton_experimento.setStatusTip(_translate("MainWindowPrincipal", "Do user experiment with own PDB", None))
        self.toolButton_experimento.setWhatsThis(_translate("MainWindowPrincipal", "Generate files to regression", None))
        self.toolButton_experimento.setAccessibleName(_translate("MainWindowPrincipal", "Experiment", None))
        self.toolButton_experimento.setText(_translate("MainWindowPrincipal", "E&xperiment", None))
        self.toolButton_ajuda.setToolTip(_translate("MainWindowPrincipal", "Help", None))
        self.toolButton_ajuda.setStatusTip(_translate("MainWindowPrincipal", "Help", None))
        self.toolButton_ajuda.setWhatsThis(_translate("MainWindowPrincipal", "Help", None))
        self.toolButton_ajuda.setAccessibleName(_translate("MainWindowPrincipal", "Help", None))
        self.toolButton_ajuda.setText(_translate("MainWindowPrincipal", "&Help", None))
        self.toolButton_informacoes.setToolTip(_translate("MainWindowPrincipal", "Tool information", None))
        self.toolButton_informacoes.setStatusTip(_translate("MainWindowPrincipal", "Downloading", None))
        self.toolButton_informacoes.setWhatsThis(_translate("MainWindowPrincipal", "Informação", None))
        self.toolButton_informacoes.setAccessibleName(_translate("MainWindowPrincipal", "Download", None))
        self.toolButton_informacoes.setText(_translate("MainWindowPrincipal", "&About", None))
        self.toolButton_sair.setToolTip(_translate("MainWindowPrincipal", "Exit this tool", None))
        self.toolButton_sair.setStatusTip(_translate("MainWindowPrincipal", "Exit this tool", None))
        self.toolButton_sair.setWhatsThis(_translate("MainWindowPrincipal", "Sair", None))
        self.toolButton_sair.setAccessibleName(_translate("MainWindowPrincipal", "sair", None))
        self.toolButton_sair.setText(_translate("MainWindowPrincipal", "&Exit", None))
        self.label.setStatusTip(_translate("MainWindowPrincipal", "Developed by Amauri Duarte and Prof. Dr. Walter F. de Azevedo Jr.", None))
        self.label.setWhatsThis(_translate("MainWindowPrincipal", "Developed by Amauri Duarte and Prof. Dr. Walter F. de Azevedo Jr.", None))
        self.label.setAccessibleName(_translate("MainWindowPrincipal", "Developed by Amauri Duarte and Prof. Dr.  Walter F. de Azevedo Jr.", None))
        self.label.setAccessibleDescription(_translate("MainWindowPrincipal", "Developed by Amauri Duarte and Prof. Dr.  Walter F. de Azevedo Jr.", None))
        self.label_version.setText(_translate("MainWindowPrincipal", "version", None))
        self.label_Titulo2.setText(_translate("MainWindowPrincipal", "<html><head/><body><p>Tool to Analyze the Binding Affinity</p></body></html>", None))
        self.toolBar.setWindowTitle(_translate("MainWindowPrincipal", "toolBar", None))
        self.actionBaixaPdbsProteinas.setText(_translate("MainWindowPrincipal", "Baixa PDBs Proteínas", None))
        self.actionGeraArquivosMedias.setText(_translate("MainWindowPrincipal", "Gera Arquivo de Médias", None))
        self.actionGeraArquivosRegressaoLinear.setText(_translate("MainWindowPrincipal", "Gera Arquivo para Regressão", None))
        self.actionFazRegressaoLinear.setText(_translate("MainWindowPrincipal", "Faz Reressão Linear", None))
        self.actionSair.setText(_translate("MainWindowPrincipal", "&Sair", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindowPrincipal = QtGui.QMainWindow()
    ui = Ui_MainWindowPrincipal()
    ui.setupUi(MainWindowPrincipal)
    MainWindowPrincipal.show()
    sys.exit(app.exec_())

