# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceBaixaPdbs.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowBaixaPdbs(object):
    def setupUi(self, MainWindowBaixaPdbs):
        MainWindowBaixaPdbs.setObjectName(_fromUtf8("MainWindowBaixaPdbs"))
        MainWindowBaixaPdbs.setWindowModality(QtCore.Qt.WindowModal)
        MainWindowBaixaPdbs.resize(900, 645)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        MainWindowBaixaPdbs.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/beagle3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowBaixaPdbs.setWindowIcon(icon)
        MainWindowBaixaPdbs.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindowBaixaPdbs)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(90, 0, 811, 77))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalLayoutWidget_2.setFont(font)
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_novo = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        self.toolButton_novo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_novo.sizePolicy().hasHeightForWidth())
        self.toolButton_novo.setSizePolicy(sizePolicy)
        self.toolButton_novo.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_novo.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setStrikeOut(False)
        font.setKerning(True)
        self.toolButton_novo.setFont(font)
        self.toolButton_novo.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_novo.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_novo.setIcon(icon1)
        self.toolButton_novo.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_novo.setAutoRepeatDelay(300)
        self.toolButton_novo.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_novo.setAutoRaise(False)
        self.toolButton_novo.setObjectName(_fromUtf8("toolButton_novo"))
        self.horizontalLayout_2.addWidget(self.toolButton_novo)
        self.toolButton_edita = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        self.toolButton_edita.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_edita.sizePolicy().hasHeightForWidth())
        self.toolButton_edita.setSizePolicy(sizePolicy)
        self.toolButton_edita.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_edita.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setStrikeOut(False)
        font.setKerning(True)
        self.toolButton_edita.setFont(font)
        self.toolButton_edita.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_edita.setAutoFillBackground(False)
        self.toolButton_edita.setIcon(icon1)
        self.toolButton_edita.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_edita.setAutoRepeatDelay(300)
        self.toolButton_edita.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_edita.setAutoRaise(False)
        self.toolButton_edita.setObjectName(_fromUtf8("toolButton_edita"))
        self.horizontalLayout_2.addWidget(self.toolButton_edita)
        self.toolButton_cancela = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        self.toolButton_cancela.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_cancela.sizePolicy().hasHeightForWidth())
        self.toolButton_cancela.setSizePolicy(sizePolicy)
        self.toolButton_cancela.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_cancela.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setStrikeOut(False)
        font.setKerning(True)
        self.toolButton_cancela.setFont(font)
        self.toolButton_cancela.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_cancela.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_cancela.setIcon(icon2)
        self.toolButton_cancela.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_cancela.setAutoRepeatDelay(300)
        self.toolButton_cancela.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_cancela.setAutoRaise(False)
        self.toolButton_cancela.setObjectName(_fromUtf8("toolButton_cancela"))
        self.horizontalLayout_2.addWidget(self.toolButton_cancela)
        self.toolButton_refina = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        self.toolButton_refina.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_refina.sizePolicy().hasHeightForWidth())
        self.toolButton_refina.setSizePolicy(sizePolicy)
        self.toolButton_refina.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_refina.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setStrikeOut(False)
        font.setKerning(True)
        self.toolButton_refina.setFont(font)
        self.toolButton_refina.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_refina.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/refinar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_refina.setIcon(icon3)
        self.toolButton_refina.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_refina.setAutoRepeatDelay(300)
        self.toolButton_refina.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_refina.setAutoRaise(False)
        self.toolButton_refina.setObjectName(_fromUtf8("toolButton_refina"))
        self.horizontalLayout_2.addWidget(self.toolButton_refina)
        self.toolButton_ClearText = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_ClearText.sizePolicy().hasHeightForWidth())
        self.toolButton_ClearText.setSizePolicy(sizePolicy)
        self.toolButton_ClearText.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_ClearText.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_ClearText.setFont(font)
        self.toolButton_ClearText.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_ClearText.setAutoFillBackground(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/Clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ClearText.setIcon(icon4)
        self.toolButton_ClearText.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_ClearText.setAutoRepeatDelay(300)
        self.toolButton_ClearText.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_ClearText.setAutoRaise(False)
        self.toolButton_ClearText.setObjectName(_fromUtf8("toolButton_ClearText"))
        self.horizontalLayout_2.addWidget(self.toolButton_ClearText)
        self.toolButton_saveText = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_saveText.sizePolicy().hasHeightForWidth())
        self.toolButton_saveText.setSizePolicy(sizePolicy)
        self.toolButton_saveText.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_saveText.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_saveText.setFont(font)
        self.toolButton_saveText.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_saveText.setAutoFillBackground(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/blue-save-disk-icon-0.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_saveText.setIcon(icon5)
        self.toolButton_saveText.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_saveText.setAutoRepeatDelay(300)
        self.toolButton_saveText.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_saveText.setAutoRaise(False)
        self.toolButton_saveText.setObjectName(_fromUtf8("toolButton_saveText"))
        self.horizontalLayout_2.addWidget(self.toolButton_saveText)
        self.toolButton_baixa = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_baixa.sizePolicy().hasHeightForWidth())
        self.toolButton_baixa.setSizePolicy(sizePolicy)
        self.toolButton_baixa.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_baixa.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_baixa.setFont(font)
        self.toolButton_baixa.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_baixa.setAutoFillBackground(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/donwload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_baixa.setIcon(icon6)
        self.toolButton_baixa.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_baixa.setAutoRepeatDelay(300)
        self.toolButton_baixa.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_baixa.setAutoRaise(False)
        self.toolButton_baixa.setObjectName(_fromUtf8("toolButton_baixa"))
        self.horizontalLayout_2.addWidget(self.toolButton_baixa)
        self.toolButton_exit = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_exit.sizePolicy().hasHeightForWidth())
        self.toolButton_exit.setSizePolicy(sizePolicy)
        self.toolButton_exit.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_exit.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_exit.setFont(font)
        self.toolButton_exit.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_exit.setAutoFillBackground(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_exit.setIcon(icon7)
        self.toolButton_exit.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_exit.setAutoRepeatDelay(300)
        self.toolButton_exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_exit.setAutoRaise(False)
        self.toolButton_exit.setObjectName(_fromUtf8("toolButton_exit"))
        self.horizontalLayout_2.addWidget(self.toolButton_exit)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 900, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtGui.QFrame.Raised)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(15, 90, 870, 55))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_experimentName = QtGui.QLabel(self.frame_2)
        self.label_experimentName.setGeometry(QtCore.QRect(10, 32, 261, 17))
        self.label_experimentName.setMinimumSize(QtCore.QSize(0, 0))
        self.label_experimentName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_experimentName.setFont(font)
        self.label_experimentName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_experimentName.setObjectName(_fromUtf8("label_experimentName"))
        self.label_quantia = QtGui.QLabel(self.frame_2)
        self.label_quantia.setGeometry(QtCore.QRect(320, 30, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_quantia.setFont(font)
        self.label_quantia.setObjectName(_fromUtf8("label_quantia"))
        self.label_outliers = QtGui.QLabel(self.frame_2)
        self.label_outliers.setGeometry(QtCore.QRect(740, 30, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_outliers.setFont(font)
        self.label_outliers.setStyleSheet(_fromUtf8(""))
        self.label_outliers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outliers.setWordWrap(True)
        self.label_outliers.setObjectName(_fromUtf8("label_outliers"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(320, 10, 171, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(740, 10, 131, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setMouseTracking(True)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_17 = QtGui.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(520, 10, 191, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_estruturaInicial = QtGui.QLabel(self.frame_2)
        self.label_estruturaInicial.setGeometry(QtCore.QRect(520, 30, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_estruturaInicial.setFont(font)
        self.label_estruturaInicial.setStyleSheet(_fromUtf8(""))
        self.label_estruturaInicial.setObjectName(_fromUtf8("label_estruturaInicial"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 141, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(15, 150, 870, 148))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_editPdb_2 = QtGui.QLabel(self.frame_3)
        self.label_editPdb_2.setGeometry(QtCore.QRect(20, 9, 191, 20))
        self.label_editPdb_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_editPdb_2.setFont(font)
        self.label_editPdb_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_editPdb_2.setObjectName(_fromUtf8("label_editPdb_2"))
        self.plainTextEdit_Comentarios = QtGui.QPlainTextEdit(self.frame_3)
        self.plainTextEdit_Comentarios.setGeometry(QtCore.QRect(20, 99, 841, 41))
        self.plainTextEdit_Comentarios.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.plainTextEdit_Comentarios.setFont(font)
        self.plainTextEdit_Comentarios.setObjectName(_fromUtf8("plainTextEdit_Comentarios"))
        self.label_editPdb_3 = QtGui.QLabel(self.frame_3)
        self.label_editPdb_3.setGeometry(QtCore.QRect(20, 80, 101, 20))
        self.label_editPdb_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_editPdb_3.setFont(font)
        self.label_editPdb_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_editPdb_3.setObjectName(_fromUtf8("label_editPdb_3"))
        self.groupBox = QtGui.QGroupBox(self.frame_3)
        self.groupBox.setGeometry(QtCore.QRect(320, 8, 171, 88))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 42))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButton_Kd = QtGui.QRadioButton(self.groupBox)
        self.radioButton_Kd.setGeometry(QtCore.QRect(55, 30, 45, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_Kd.setFont(font)
        self.radioButton_Kd.setObjectName(_fromUtf8("radioButton_Kd"))
        self.radioButton_Ki = QtGui.QRadioButton(self.groupBox)
        self.radioButton_Ki.setGeometry(QtCore.QRect(5, 30, 40, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_Ki.setFont(font)
        self.radioButton_Ki.setChecked(True)
        self.radioButton_Ki.setObjectName(_fromUtf8("radioButton_Ki"))
        self.radioButton_IC50 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_IC50.setGeometry(QtCore.QRect(100, 30, 61, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_IC50.setFont(font)
        self.radioButton_IC50.setObjectName(_fromUtf8("radioButton_IC50"))
        self.radioButton_EC50 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_EC50.setGeometry(QtCore.QRect(6, 60, 65, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_EC50.setFont(font)
        self.radioButton_EC50.setObjectName(_fromUtf8("radioButton_EC50"))
        self.radioButton_deltaG = QtGui.QRadioButton(self.groupBox)
        self.radioButton_deltaG.setGeometry(QtCore.QRect(80, 60, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_deltaG.setFont(font)
        self.radioButton_deltaG.setObjectName(_fromUtf8("radioButton_deltaG"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 8, 141, 88))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setUnderline(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButton_training = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_training.setGeometry(QtCore.QRect(6, 30, 131, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_training.setFont(font)
        self.radioButton_training.setChecked(True)
        self.radioButton_training.setObjectName(_fromUtf8("radioButton_training"))
        self.radioButton_individual = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_individual.setGeometry(QtCore.QRect(6, 60, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_individual.setFont(font)
        self.radioButton_individual.setObjectName(_fromUtf8("radioButton_individual"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_3.setGeometry(QtCore.QRect(670, 8, 201, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setUnderline(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.checkBox_eliminateLigand = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_eliminateLigand.setGeometry(QtCore.QRect(5, 30, 91, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_eliminateLigand.sizePolicy().hasHeightForWidth())
        self.checkBox_eliminateLigand.setSizePolicy(sizePolicy)
        self.checkBox_eliminateLigand.setObjectName(_fromUtf8("checkBox_eliminateLigand"))
        self.plainTextEdit_descricao = QtGui.QPlainTextEdit(self.frame_3)
        self.plainTextEdit_descricao.setGeometry(QtCore.QRect(20, 29, 281, 41))
        self.plainTextEdit_descricao.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.plainTextEdit_descricao.setFont(font)
        self.plainTextEdit_descricao.setObjectName(_fromUtf8("plainTextEdit_descricao"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(15, 490, 870, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.progressBar = QtGui.QProgressBar(self.frame_4)
        self.progressBar.setGeometry(QtCore.QRect(20, 31, 841, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_cabecalho = QtGui.QLabel(self.frame_4)
        self.label_cabecalho.setGeometry(QtCore.QRect(20, 11, 691, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_cabecalho.setFont(font)
        self.label_cabecalho.setObjectName(_fromUtf8("label_cabecalho"))
        self.label_textoProgresso = QtGui.QLabel(self.frame_4)
        self.label_textoProgresso.setGeometry(QtCore.QRect(120, 50, 491, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_textoProgresso.setFont(font)
        self.label_textoProgresso.setObjectName(_fromUtf8("label_textoProgresso"))
        self.label_editPdb_4 = QtGui.QLabel(self.frame_4)
        self.label_editPdb_4.setGeometry(QtCore.QRect(20, 49, 101, 20))
        self.label_editPdb_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_editPdb_4.setFont(font)
        self.label_editPdb_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_editPdb_4.setObjectName(_fromUtf8("label_editPdb_4"))
        self.label_relogio = QtGui.QLabel(self.centralwidget)
        self.label_relogio.setGeometry(QtCore.QRect(869, 467, 32, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_relogio.setFont(font)
        self.label_relogio.setAutoFillBackground(False)
        self.label_relogio.setText(_fromUtf8(""))
        self.label_relogio.setPixmap(QtGui.QPixmap(_fromUtf8("img/relogio.png")))
        self.label_relogio.setScaledContents(True)
        self.label_relogio.setObjectName(_fromUtf8("label_relogio"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 570, 871, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 251, 202);"))
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_6 = QtGui.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 861, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setToolTip(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(15, 306, 870, 176))
        self.frame.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_editPdbTest = QtGui.QLabel(self.frame)
        self.label_editPdbTest.setGeometry(QtCore.QRect(500, 61, 231, 20))
        self.label_editPdbTest.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_editPdbTest.setFont(font)
        self.label_editPdbTest.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_editPdbTest.setStyleSheet(_fromUtf8("color: rgb(27, 107, 11);"))
        self.label_editPdbTest.setObjectName(_fromUtf8("label_editPdbTest"))
        self.label_editPdb = QtGui.QLabel(self.frame)
        self.label_editPdb.setGeometry(QtCore.QRect(11, 61, 331, 20))
        self.label_editPdb.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_editPdb.setFont(font)
        self.label_editPdb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_editPdb.setObjectName(_fromUtf8("label_editPdb"))
        self.plainTextEdit_pdbs = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit_pdbs.setGeometry(QtCore.QRect(10, 82, 475, 85))
        self.plainTextEdit_pdbs.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.plainTextEdit_pdbs.setFont(font)
        self.plainTextEdit_pdbs.setToolTip(_fromUtf8(""))
        self.plainTextEdit_pdbs.setObjectName(_fromUtf8("plainTextEdit_pdbs"))
        self.plainTextEdit_pdbsTestSet = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit_pdbsTestSet.setGeometry(QtCore.QRect(500, 82, 355, 85))
        self.plainTextEdit_pdbsTestSet.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.plainTextEdit_pdbsTestSet.setFont(font)
        self.plainTextEdit_pdbsTestSet.setToolTip(_fromUtf8(""))
        self.plainTextEdit_pdbsTestSet.setStyleSheet(_fromUtf8("color: rgb(27, 107, 11);"))
        self.plainTextEdit_pdbsTestSet.setObjectName(_fromUtf8("plainTextEdit_pdbsTestSet"))
        self.groupBox_PdbEntrada = QtGui.QGroupBox(self.frame)
        self.groupBox_PdbEntrada.setGeometry(QtCore.QRect(10, 9, 541, 45))
        self.groupBox_PdbEntrada.setObjectName(_fromUtf8("groupBox_PdbEntrada"))
        self.radioButton_unico = QtGui.QRadioButton(self.groupBox_PdbEntrada)
        self.radioButton_unico.setGeometry(QtCore.QRect(0, 20, 281, 23))
        self.radioButton_unico.setObjectName(_fromUtf8("radioButton_unico"))
        self.radioButton_trainingTest = QtGui.QRadioButton(self.groupBox_PdbEntrada)
        self.radioButton_trainingTest.setGeometry(QtCore.QRect(310, 20, 221, 23))
        self.radioButton_trainingTest.setObjectName(_fromUtf8("radioButton_trainingTest"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 90, 65))
        self.label_27.setMaximumSize(QtCore.QSize(90, 65))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("img/TabaComLetras.png")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.line_2.raise_()
        self.frame_5.raise_()
        self.frame.raise_()
        self.label_relogio.raise_()
        self.label_27.raise_()
        MainWindowBaixaPdbs.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowBaixaPdbs)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindowBaixaPdbs.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowBaixaPdbs)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowBaixaPdbs.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowBaixaPdbs)
        QtCore.QObject.connect(self.toolButton_ClearText, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.limpaTexto)
        QtCore.QObject.connect(self.toolButton_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.sair)
        QtCore.QObject.connect(self.toolButton_saveText, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.salva)
        QtCore.QObject.connect(self.toolButton_baixa, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.baixaPdb)
        QtCore.QObject.connect(self.toolButton_edita, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.edita)
        QtCore.QObject.connect(self.toolButton_cancela, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.cancela)
        QtCore.QObject.connect(self.toolButton_refina, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.retira)
        QtCore.QObject.connect(self.toolButton_novo, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.novo)
        QtCore.QObject.connect(self.checkBox_eliminateLigand, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.mensagemExcluiLigante)
        QtCore.QObject.connect(self.radioButton_unico, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.insereTrainingTestSet)
        QtCore.QObject.connect(self.radioButton_trainingTest, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowBaixaPdbs.insereTrainingTestSet)
        QtCore.QMetaObject.connectSlotsByName(MainWindowBaixaPdbs)

    def retranslateUi(self, MainWindowBaixaPdbs):
        MainWindowBaixaPdbs.setWindowTitle(_translate("MainWindowBaixaPdbs", "Handle PDB Structure", None))
        MainWindowBaixaPdbs.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p><br/></p></body></html>", None))
        self.toolButton_novo.setToolTip(_translate("MainWindowBaixaPdbs", "Create a nex experiment", None))
        self.toolButton_novo.setStatusTip(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_novo.setWhatsThis(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_novo.setAccessibleName(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_novo.setText(_translate("MainWindowBaixaPdbs", "&New", None))
        self.toolButton_edita.setToolTip(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_edita.setStatusTip(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_edita.setWhatsThis(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_edita.setAccessibleName(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_edita.setText(_translate("MainWindowBaixaPdbs", "E&dit", None))
        self.toolButton_cancela.setToolTip(_translate("MainWindowBaixaPdbs", "Calcel edit", None))
        self.toolButton_cancela.setStatusTip(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_cancela.setWhatsThis(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_cancela.setAccessibleName(_translate("MainWindowBaixaPdbs", "Edit informations about PDB", None))
        self.toolButton_cancela.setText(_translate("MainWindowBaixaPdbs", "&Cancel", None))
        self.toolButton_refina.setToolTip(_translate("MainWindowBaixaPdbs", "Removes repeated structures", None))
        self.toolButton_refina.setStatusTip(_translate("MainWindowBaixaPdbs", "Removes repeated structures", None))
        self.toolButton_refina.setWhatsThis(_translate("MainWindowBaixaPdbs", "Removes repeated structures", None))
        self.toolButton_refina.setAccessibleName(_translate("MainWindowBaixaPdbs", "Removes repeated structures", None))
        self.toolButton_refina.setText(_translate("MainWindowBaixaPdbs", "Refi&ne", None))
        self.toolButton_ClearText.setToolTip(_translate("MainWindowBaixaPdbs", "Clear text PDBs", None))
        self.toolButton_ClearText.setStatusTip(_translate("MainWindowBaixaPdbs", "Clear text PDBs", None))
        self.toolButton_ClearText.setWhatsThis(_translate("MainWindowBaixaPdbs", "Clear text PDBs", None))
        self.toolButton_ClearText.setAccessibleName(_translate("MainWindowBaixaPdbs", "Download", None))
        self.toolButton_ClearText.setText(_translate("MainWindowBaixaPdbs", "Clea&r Text", None))
        self.toolButton_saveText.setToolTip(_translate("MainWindowBaixaPdbs", "Save PDB List", None))
        self.toolButton_saveText.setStatusTip(_translate("MainWindowBaixaPdbs", "Saving", None))
        self.toolButton_saveText.setWhatsThis(_translate("MainWindowBaixaPdbs", "Save Pdbs", None))
        self.toolButton_saveText.setAccessibleName(_translate("MainWindowBaixaPdbs", "Save", None))
        self.toolButton_saveText.setText(_translate("MainWindowBaixaPdbs", "&Save", None))
        self.toolButton_baixa.setToolTip(_translate("MainWindowBaixaPdbs", "Download PDB List", None))
        self.toolButton_baixa.setStatusTip(_translate("MainWindowBaixaPdbs", "Downloading", None))
        self.toolButton_baixa.setWhatsThis(_translate("MainWindowBaixaPdbs", "Download Pdbs", None))
        self.toolButton_baixa.setAccessibleName(_translate("MainWindowBaixaPdbs", "Save", None))
        self.toolButton_baixa.setText(_translate("MainWindowBaixaPdbs", "&Download", None))
        self.toolButton_exit.setToolTip(_translate("MainWindowBaixaPdbs", "Exit download PDB", None))
        self.toolButton_exit.setStatusTip(_translate("MainWindowBaixaPdbs", "Exiting", None))
        self.toolButton_exit.setWhatsThis(_translate("MainWindowBaixaPdbs", "Exit", None))
        self.toolButton_exit.setAccessibleName(_translate("MainWindowBaixaPdbs", "Save", None))
        self.toolButton_exit.setText(_translate("MainWindowBaixaPdbs", "&Exit", None))
        self.label_experimentName.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>The experiment name is assigned when saved in &quot;Manage Experiments&quot;.</p></body></html>", None))
        self.label_experimentName.setText(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>Experiment name</p></body></html>", None))
        self.label_quantia.setText(_translate("MainWindowBaixaPdbs", "TextLabel", None))
        self.label_outliers.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>If &quot;yes&quot;, the outliers have already been deleted</p></body></html>", None))
        self.label_outliers.setText(_translate("MainWindowBaixaPdbs", "TextLabel", None))
        self.label_9.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>This is the value after the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_9.setText(_translate("MainWindowBaixaPdbs", "Number of Structures", None))
        self.label_11.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>If &quot;yes&quot;, the outliers have already been deleted</p></body></html>", None))
        self.label_11.setText(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>Deleted Outliers</p></body></html>", None))
        self.label_17.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>This is the value before the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_17.setText(_translate("MainWindowBaixaPdbs", "Initial Number Structures", None))
        self.label_estruturaInicial.setText(_translate("MainWindowBaixaPdbs", "TextLabel", None))
        self.label_10.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>The experiment name is assigned when saved in &quot;Manage Experiments&quot;.</p></body></html>", None))
        self.label_10.setText(_translate("MainWindowBaixaPdbs", "Experiment Name", None))
        self.label_editPdb_2.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>Protein system name</p></body></html>", None))
        self.label_editPdb_2.setText(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>Protein System Name</p></body></html>", None))
        self.plainTextEdit_Comentarios.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>Enter the comments about this experiment</p></body></html>", None))
        self.label_editPdb_3.setText(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>Comments</p></body></html>", None))
        self.groupBox.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>Select the type of inhibitor</p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindowBaixaPdbs", "Affinity Type", None))
        self.radioButton_Kd.setText(_translate("MainWindowBaixaPdbs", "Kd", None))
        self.radioButton_Ki.setText(_translate("MainWindowBaixaPdbs", "Ki", None))
        self.radioButton_IC50.setText(_translate("MainWindowBaixaPdbs", "IC50", None))
        self.radioButton_EC50.setText(_translate("MainWindowBaixaPdbs", "EC50", None))
        self.radioButton_deltaG.setToolTip(_translate("MainWindowBaixaPdbs", "delta G", None))
        self.radioButton_deltaG.setText(_translate("MainWindowBaixaPdbs", "Delta G", None))
        self.groupBox_2.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>if &quot;training&quot; is marked, only the training set will be considered to calculate the average distance</p></body></html>", None))
        self.groupBox_2.setTitle(_translate("MainWindowBaixaPdbs", "Average Type", None))
        self.radioButton_training.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>If &quot;training&quot; is marked, only the means of the training sets will be considered in the calculations of the energy terms</p></body></html>", None))
        self.radioButton_training.setText(_translate("MainWindowBaixaPdbs", "Training set only", None))
        self.radioButton_individual.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>If &quot;both sets&quot; is marked, the means of the training and test sets will be considered in the calculations of the energy terms</p></body></html>", None))
        self.radioButton_individual.setText(_translate("MainWindowBaixaPdbs", "Both sets", None))
        self.groupBox_3.setToolTip(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>If it is disabled, it is because you can not delete repeated ligands or because this has already been done</p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindowBaixaPdbs", "Eliminate Repeated Ligands  ", None))
        self.checkBox_eliminateLigand.setToolTip(_translate("MainWindowBaixaPdbs", "Eliminate repeated ligands", None))
        self.checkBox_eliminateLigand.setText(_translate("MainWindowBaixaPdbs", "Yes", None))
        self.plainTextEdit_descricao.setToolTip(_translate("MainWindowBaixaPdbs", "Enter the name to identify the experiment", None))
        self.plainTextEdit_descricao.setStatusTip(_translate("MainWindowBaixaPdbs", "Enter the name to identify the experiment", None))
        self.plainTextEdit_descricao.setWhatsThis(_translate("MainWindowBaixaPdbs", "Enter the name to identify the experiment", None))
        self.label_cabecalho.setText(_translate("MainWindowBaixaPdbs", "TextLabel", None))
        self.label_textoProgresso.setText(_translate("MainWindowBaixaPdbs", "TextLabel", None))
        self.label_editPdb_4.setText(_translate("MainWindowBaixaPdbs", "<html><head/><body><p>Download file:</p></body></html>", None))
        self.label_relogio.setToolTip(_translate("MainWindowBaixaPdbs", "Operation in progress. Wait please !", None))
        self.label_6.setText(_translate("MainWindowBaixaPdbs", "<html><head/><body><p><span style=\" font-weight:600;\">Notes: </span><span style=\" font-size:10pt;\">#1: In some situations, there may be repeated structures. Press </span><span style=\" font-size:10pt; font-weight:600;\">Refine</span><span style=\" font-size:10pt;\"> to remove them. Previous results will be removed.</span><br/><span style=\" font-size:10pt;\">#2: After saving a experiment, the only way to change the</span><span style=\" font-size:10pt; font-weight:600;\"> Affinity Type, Average Type </span><span style=\" font-size:10pt;\">and</span><span style=\" font-size:10pt; font-weight:600;\"> Eliminate Repeated Ligands </span><span style=\" font-size:10pt;\">is to create a new one.</span></p><p><br/></p></body></html>", None))
        self.label_editPdbTest.setText(_translate("MainWindowBaixaPdbs", "PDBs to Download (Test set)", None))
        self.label_editPdb.setText(_translate("MainWindowBaixaPdbs", "PDBs to Download", None))
        self.groupBox_PdbEntrada.setTitle(_translate("MainWindowBaixaPdbs", "PDBs Entries", None))
        self.radioButton_unico.setText(_translate("MainWindowBaixaPdbs", "Lets Taba define Training and Test Sets", None))
        self.radioButton_trainingTest.setText(_translate("MainWindowBaixaPdbs", "Define Training and Test Sets", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindowBaixaPdbs = QtGui.QMainWindow()
    ui = Ui_MainWindowBaixaPdbs()
    ui.setupUi(MainWindowBaixaPdbs)
    MainWindowBaixaPdbs.show()
    sys.exit(app.exec_())

