# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceGeraArquivosRegressao.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowGeraArquivos(object):
    def setupUi(self, MainWindowGeraArquivos):
        MainWindowGeraArquivos.setObjectName(_fromUtf8("MainWindowGeraArquivos"))
        MainWindowGeraArquivos.setWindowModality(QtCore.Qt.WindowModal)
        MainWindowGeraArquivos.resize(900, 500)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        MainWindowGeraArquivos.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/beagle3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowGeraArquivos.setWindowIcon(icon)
        MainWindowGeraArquivos.setToolTip(_fromUtf8(""))
        MainWindowGeraArquivos.setIconSize(QtCore.QSize(32, 32))
        MainWindowGeraArquivos.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindowGeraArquivos)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(90, 0, 821, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalLayoutWidget_2.setFont(font)
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_iniciar = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_iniciar.sizePolicy().hasHeightForWidth())
        self.toolButton_iniciar.setSizePolicy(sizePolicy)
        self.toolButton_iniciar.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_iniciar.setMaximumSize(QtCore.QSize(85, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.toolButton_iniciar.setFont(font)
        self.toolButton_iniciar.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_iniciar.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/iniciar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_iniciar.setIcon(icon1)
        self.toolButton_iniciar.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_iniciar.setAutoRepeatDelay(300)
        self.toolButton_iniciar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_iniciar.setAutoRaise(False)
        self.toolButton_iniciar.setObjectName(_fromUtf8("toolButton_iniciar"))
        self.horizontalLayout_2.addWidget(self.toolButton_iniciar)
        self.toolButton_exit = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_exit.sizePolicy().hasHeightForWidth())
        self.toolButton_exit.setSizePolicy(sizePolicy)
        self.toolButton_exit.setMinimumSize(QtCore.QSize(65, 65))
        self.toolButton_exit.setMaximumSize(QtCore.QSize(85, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.toolButton_exit.setFont(font)
        self.toolButton_exit.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_exit.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_exit.setIcon(icon2)
        self.toolButton_exit.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_exit.setAutoRepeatDelay(300)
        self.toolButton_exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_exit.setAutoRaise(False)
        self.toolButton_exit.setObjectName(_fromUtf8("toolButton_exit"))
        self.horizontalLayout_2.addWidget(self.toolButton_exit)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 900, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtGui.QFrame.Raised)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(15, 190, 870, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_distanciaUsada = QtGui.QLabel(self.frame)
        self.label_distanciaUsada.setGeometry(QtCore.QRect(449, 14, 271, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_distanciaUsada.setFont(font)
        self.label_distanciaUsada.setObjectName(_fromUtf8("label_distanciaUsada"))
        self.label_distanciasUsadas = QtGui.QLabel(self.frame)
        self.label_distanciasUsadas.setGeometry(QtCore.QRect(450, 44, 261, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_distanciasUsadas.setFont(font)
        self.label_distanciasUsadas.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label_distanciasUsadas.setObjectName(_fromUtf8("label_distanciasUsadas"))
        self.comboBox_seed = QtGui.QComboBox(self.frame)
        self.comboBox_seed.setGeometry(QtCore.QRect(750, 38, 100, 30))
        self.comboBox_seed.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox_seed.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.comboBox_seed.setFont(font)
        self.comboBox_seed.setObjectName(_fromUtf8("comboBox_seed"))
        self.comboBox_seed.addItem(_fromUtf8(""))
        self.comboBox_seed.addItem(_fromUtf8(""))
        self.comboBox_seed.addItem(_fromUtf8(""))
        self.comboBox_seed.addItem(_fromUtf8(""))
        self.comboBox_seed.addItem(_fromUtf8(""))
        self.comboBox_seed.addItem(_fromUtf8(""))
        self.comboBox_seed.addItem(_fromUtf8(""))
        self.comboBox_seed.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(750, 14, 60, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(20, 14, 421, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setUnderline(False)
        self.groupBox.setFont(font)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButton_35 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_35.setGeometry(QtCore.QRect(0, 30, 45, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_35.setFont(font)
        self.radioButton_35.setObjectName(_fromUtf8("radioButton_35"))
        self.radioButton_45 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_45.setGeometry(QtCore.QRect(55, 30, 45, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_45.setFont(font)
        self.radioButton_45.setChecked(True)
        self.radioButton_45.setObjectName(_fromUtf8("radioButton_45"))
        self.radioButton_60 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_60.setGeometry(QtCore.QRect(110, 30, 45, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_60.setFont(font)
        self.radioButton_60.setObjectName(_fromUtf8("radioButton_60"))
        self.radioButton_75 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_75.setGeometry(QtCore.QRect(165, 30, 45, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_75.setFont(font)
        self.radioButton_75.setObjectName(_fromUtf8("radioButton_75"))
        self.radioButton_90 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_90.setGeometry(QtCore.QRect(230, 30, 45, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_90.setFont(font)
        self.radioButton_90.setObjectName(_fromUtf8("radioButton_90"))
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(-20, 60, 800, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.radioButton_120 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_120.setGeometry(QtCore.QRect(285, 30, 55, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_120.setFont(font)
        self.radioButton_120.setObjectName(_fromUtf8("radioButton_120"))
        self.radioButton_150 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_150.setGeometry(QtCore.QRect(350, 30, 55, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_150.setFont(font)
        self.radioButton_150.setObjectName(_fromUtf8("radioButton_150"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(15, 283, 870, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.progressBar = QtGui.QProgressBar(self.frame_2)
        self.progressBar.setGeometry(QtCore.QRect(20, 30, 831, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_textoProgresso = QtGui.QLabel(self.frame_2)
        self.label_textoProgresso.setGeometry(QtCore.QRect(20, 50, 671, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_textoProgresso.setFont(font)
        self.label_textoProgresso.setObjectName(_fromUtf8("label_textoProgresso"))
        self.label_cabecalho = QtGui.QLabel(self.frame_2)
        self.label_cabecalho.setGeometry(QtCore.QRect(20, 10, 721, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_cabecalho.setFont(font)
        self.label_cabecalho.setObjectName(_fromUtf8("label_cabecalho"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(25, 370, 850, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 251, 202);"))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 6, 850, 70))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setToolTip(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(15, 93, 870, 85))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(540, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(446, 10, 61, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_afinidade = QtGui.QLabel(self.frame_4)
        self.label_afinidade.setGeometry(QtCore.QRect(450, 52, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_afinidade.setFont(font)
        self.label_afinidade.setObjectName(_fromUtf8("label_afinidade"))
        self.label_quantia = QtGui.QLabel(self.frame_4)
        self.label_quantia.setGeometry(QtCore.QRect(540, 52, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_quantia.setFont(font)
        self.label_quantia.setStyleSheet(_fromUtf8(""))
        self.label_quantia.setObjectName(_fromUtf8("label_quantia"))
        self.label_system = QtGui.QLabel(self.frame_4)
        self.label_system.setGeometry(QtCore.QRect(20, 52, 281, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_system.setFont(font)
        self.label_system.setObjectName(_fromUtf8("label_system"))
        self.label_experimento_2 = QtGui.QLabel(self.frame_4)
        self.label_experimento_2.setGeometry(QtCore.QRect(20, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_experimento_2.setFont(font)
        self.label_experimento_2.setWordWrap(True)
        self.label_experimento_2.setObjectName(_fromUtf8("label_experimento_2"))
        self.label_experimento_3 = QtGui.QLabel(self.frame_4)
        self.label_experimento_3.setGeometry(QtCore.QRect(320, 10, 71, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_experimento_3.setFont(font)
        self.label_experimento_3.setWordWrap(True)
        self.label_experimento_3.setObjectName(_fromUtf8("label_experimento_3"))
        self.label_tipoMedia = QtGui.QLabel(self.frame_4)
        self.label_tipoMedia.setGeometry(QtCore.QRect(320, 52, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_tipoMedia.setFont(font)
        self.label_tipoMedia.setObjectName(_fromUtf8("label_tipoMedia"))
        self.label_outliers = QtGui.QLabel(self.frame_4)
        self.label_outliers.setGeometry(QtCore.QRect(798, 52, 50, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_outliers.setFont(font)
        self.label_outliers.setStyleSheet(_fromUtf8(""))
        self.label_outliers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outliers.setWordWrap(False)
        self.label_outliers.setObjectName(_fromUtf8("label_outliers"))
        self.label_11 = QtGui.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(798, 15, 71, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_estruturaInicial = QtGui.QLabel(self.frame_4)
        self.label_estruturaInicial.setGeometry(QtCore.QRect(650, 52, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_estruturaInicial.setFont(font)
        self.label_estruturaInicial.setStyleSheet(_fromUtf8(""))
        self.label_estruturaInicial.setObjectName(_fromUtf8("label_estruturaInicial"))
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(650, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_relogio = QtGui.QLabel(self.centralwidget)
        self.label_relogio.setGeometry(QtCore.QRect(869, 270, 32, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_relogio.setFont(font)
        self.label_relogio.setAutoFillBackground(False)
        self.label_relogio.setText(_fromUtf8(""))
        self.label_relogio.setPixmap(QtGui.QPixmap(_fromUtf8("img/relogio.png")))
        self.label_relogio.setScaledContents(True)
        self.label_relogio.setObjectName(_fromUtf8("label_relogio"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 90, 65))
        self.label_27.setMaximumSize(QtCore.QSize(90, 65))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("img/TabaComLetras.png")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.frame_2.raise_()
        self.frame.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.line_2.raise_()
        self.frame_4.raise_()
        self.label_relogio.raise_()
        self.frame_3.raise_()
        self.label_27.raise_()
        MainWindowGeraArquivos.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowGeraArquivos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindowGeraArquivos.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowGeraArquivos)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowGeraArquivos.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowGeraArquivos)
        QtCore.QObject.connect(self.toolButton_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowGeraArquivos.sair)
        QtCore.QObject.connect(self.toolButton_iniciar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowGeraArquivos.geraArquivosTermoEnergia)
        QtCore.QMetaObject.connectSlotsByName(MainWindowGeraArquivos)

    def retranslateUi(self, MainWindowGeraArquivos):
        MainWindowGeraArquivos.setWindowTitle(_translate("MainWindowGeraArquivos", "Generates File for Regression", None))
        self.toolButton_iniciar.setToolTip(_translate("MainWindowGeraArquivos", "Starting generate files with energy terms", None))
        self.toolButton_iniciar.setStatusTip(_translate("MainWindowGeraArquivos", "Downloading", None))
        self.toolButton_iniciar.setWhatsThis(_translate("MainWindowGeraArquivos", "Start experiment", None))
        self.toolButton_iniciar.setAccessibleName(_translate("MainWindowGeraArquivos", "start", None))
        self.toolButton_iniciar.setText(_translate("MainWindowGeraArquivos", "&Start", None))
        self.toolButton_exit.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>Exit this window</p></body></html>", None))
        self.toolButton_exit.setStatusTip(_translate("MainWindowGeraArquivos", "Exit Experiment", None))
        self.toolButton_exit.setWhatsThis(_translate("MainWindowGeraArquivos", "Exit", None))
        self.toolButton_exit.setAccessibleName(_translate("MainWindowGeraArquivos", "Save", None))
        self.toolButton_exit.setText(_translate("MainWindowGeraArquivos", "&Exit", None))
        self.label_distanciaUsada.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>The linear regressions files for these cut distances was already generated.</p></body></html>", None))
        self.label_distanciaUsada.setText(_translate("MainWindowGeraArquivos", "Cut Distances Already Used", None))
        self.label_distanciasUsadas.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>The linear regressions files for these cut distances was already generated.</p></body></html>", None))
        self.label_distanciasUsadas.setText(_translate("MainWindowGeraArquivos", "null", None))
        self.comboBox_seed.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>Choose the seed to generate aleatory training set and aleatory test set.</p></body></html>", None))
        self.comboBox_seed.setItemText(0, _translate("MainWindowGeraArquivos", "27950288", None))
        self.comboBox_seed.setItemText(1, _translate("MainWindowGeraArquivos", "2643383", None))
        self.comboBox_seed.setItemText(2, _translate("MainWindowGeraArquivos", "323846", None))
        self.comboBox_seed.setItemText(3, _translate("MainWindowGeraArquivos", "58979", None))
        self.comboBox_seed.setItemText(4, _translate("MainWindowGeraArquivos", "2653", None))
        self.comboBox_seed.setItemText(5, _translate("MainWindowGeraArquivos", "159", None))
        self.comboBox_seed.setItemText(6, _translate("MainWindowGeraArquivos", "14", None))
        self.comboBox_seed.setItemText(7, _translate("MainWindowGeraArquivos", "3", None))
        self.label.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>Choose the seed to generate aleatory training set and aleatory test set.</p></body></html>", None))
        self.label.setText(_translate("MainWindowGeraArquivos", "Seed", None))
        self.groupBox.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>Select the cut distance (in Angstrons) betwin ligand and protein to be considered.</p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindowGeraArquivos", "Cut Distance in Angstrons", None))
        self.radioButton_35.setText(_translate("MainWindowGeraArquivos", "3.5", None))
        self.radioButton_45.setText(_translate("MainWindowGeraArquivos", "4.5", None))
        self.radioButton_60.setText(_translate("MainWindowGeraArquivos", "6.0", None))
        self.radioButton_75.setText(_translate("MainWindowGeraArquivos", "7.5", None))
        self.radioButton_90.setText(_translate("MainWindowGeraArquivos", "9.0", None))
        self.radioButton_120.setText(_translate("MainWindowGeraArquivos", "12.0", None))
        self.radioButton_150.setText(_translate("MainWindowGeraArquivos", "15.0", None))
        self.label_textoProgresso.setText(_translate("MainWindowGeraArquivos", "TextLabel", None))
        self.label_cabecalho.setText(_translate("MainWindowGeraArquivos", "TextLabel", None))
        self.label_6.setText(_translate("MainWindowGeraArquivos", "<html><head/><body><p><span style=\" font-weight:600;\">Notes:</span></p><p>#1:This function generates files with energy terms in two steps. The first one is used to create the training set and the second the test set.<br/>#2: The test set files are in: TABA/inputFiles/pdbsProteinaFinalTes.txt<br/>#3: The training set files are in: TABA/inputFiles/pdbsProteinaFinalTre.txt</p></body></html>", None))
        self.label_9.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>This is the value after the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_9.setText(_translate("MainWindowGeraArquivos", "Number Structures", None))
        self.label_8.setText(_translate("MainWindowGeraArquivos", "Affinity Type", None))
        self.label_afinidade.setText(_translate("MainWindowGeraArquivos", "TextLabel", None))
        self.label_quantia.setText(_translate("MainWindowGeraArquivos", "TextLabel", None))
        self.label_system.setText(_translate("MainWindowGeraArquivos", "TextLabel", None))
        self.label_experimento_2.setText(_translate("MainWindowGeraArquivos", "<html><head/><body><p>Protein System Name</p></body></html>", None))
        self.label_experimento_3.setText(_translate("MainWindowGeraArquivos", "Average Type", None))
        self.label_tipoMedia.setToolTip(_translate("MainWindowGeraArquivos", "Average Type", None))
        self.label_tipoMedia.setText(_translate("MainWindowGeraArquivos", "TextLabel", None))
        self.label_outliers.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>If &quot;yes&quot;, the outliers have already been deleted</p></body></html>", None))
        self.label_outliers.setText(_translate("MainWindowGeraArquivos", "TextLabel", None))
        self.label_11.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>If &quot;yes&quot;, the outliers have already been deleted</p></body></html>", None))
        self.label_11.setText(_translate("MainWindowGeraArquivos", "<html><head/><body><p>Deleted Outliers</p></body></html>", None))
        self.label_estruturaInicial.setText(_translate("MainWindowGeraArquivos", "TextLabel", None))
        self.label_10.setToolTip(_translate("MainWindowGeraArquivos", "<html><head/><body><p>This is the value before the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_10.setText(_translate("MainWindowGeraArquivos", "Initial Number Structures", None))
        self.label_relogio.setToolTip(_translate("MainWindowGeraArquivos", "Operation in progress. Wait please !", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindowGeraArquivos = QtGui.QMainWindow()
    ui = Ui_MainWindowGeraArquivos()
    ui.setupUi(MainWindowGeraArquivos)
    MainWindowGeraArquivos.show()
    sys.exit(app.exec_())

