# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceCorrelacao.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_correlacao(object):
    def setupUi(self, MainWindow_correlacao):
        MainWindow_correlacao.setObjectName(_fromUtf8("MainWindow_correlacao"))
        MainWindow_correlacao.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow_correlacao.resize(1000, 670)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        MainWindow_correlacao.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/beagle3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_correlacao.setWindowIcon(icon)
        MainWindow_correlacao.setToolTip(_fromUtf8(""))
        MainWindow_correlacao.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow_correlacao)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(80, 0, 921, 77))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(58)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_4.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_4.setMinimumSize(QtCore.QSize(0, 58))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalLayoutWidget_4.setFont(font)
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_iniciar = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_iniciar.sizePolicy().hasHeightForWidth())
        self.toolButton_iniciar.setSizePolicy(sizePolicy)
        self.toolButton_iniciar.setMinimumSize(QtCore.QSize(80, 65))
        self.toolButton_iniciar.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_iniciar.setFont(font)
        self.toolButton_iniciar.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_iniciar.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/iniciar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_iniciar.setIcon(icon1)
        self.toolButton_iniciar.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_iniciar.setAutoRepeatDelay(300)
        self.toolButton_iniciar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_iniciar.setAutoRaise(False)
        self.toolButton_iniciar.setObjectName(_fromUtf8("toolButton_iniciar"))
        self.horizontalLayout_2.addWidget(self.toolButton_iniciar)
        self.toolButton_tuning = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_tuning.sizePolicy().hasHeightForWidth())
        self.toolButton_tuning.setSizePolicy(sizePolicy)
        self.toolButton_tuning.setMinimumSize(QtCore.QSize(80, 65))
        self.toolButton_tuning.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_tuning.setFont(font)
        self.toolButton_tuning.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/ajuste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_tuning.setIcon(icon2)
        self.toolButton_tuning.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_tuning.setAutoRepeatDelay(300)
        self.toolButton_tuning.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_tuning.setAutoRaise(False)
        self.toolButton_tuning.setObjectName(_fromUtf8("toolButton_tuning"))
        self.horizontalLayout_2.addWidget(self.toolButton_tuning)
        self.toolButton_graficos = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_graficos.sizePolicy().hasHeightForWidth())
        self.toolButton_graficos.setSizePolicy(sizePolicy)
        self.toolButton_graficos.setMinimumSize(QtCore.QSize(80, 65))
        self.toolButton_graficos.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_graficos.setFont(font)
        self.toolButton_graficos.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_graficos.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/grafico.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_graficos.setIcon(icon3)
        self.toolButton_graficos.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_graficos.setAutoRepeatDelay(300)
        self.toolButton_graficos.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_graficos.setAutoRaise(False)
        self.toolButton_graficos.setObjectName(_fromUtf8("toolButton_graficos"))
        self.horizontalLayout_2.addWidget(self.toolButton_graficos)
        self.toolButton_outlier = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_outlier.sizePolicy().hasHeightForWidth())
        self.toolButton_outlier.setSizePolicy(sizePolicy)
        self.toolButton_outlier.setMinimumSize(QtCore.QSize(80, 65))
        self.toolButton_outlier.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_outlier.setFont(font)
        self.toolButton_outlier.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_outlier.setAutoFillBackground(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/filter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_outlier.setIcon(icon4)
        self.toolButton_outlier.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_outlier.setAutoRepeatDelay(300)
        self.toolButton_outlier.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_outlier.setAutoRaise(False)
        self.toolButton_outlier.setObjectName(_fromUtf8("toolButton_outlier"))
        self.horizontalLayout_2.addWidget(self.toolButton_outlier)
        self.toolButton_exit = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_exit.sizePolicy().hasHeightForWidth())
        self.toolButton_exit.setSizePolicy(sizePolicy)
        self.toolButton_exit.setMinimumSize(QtCore.QSize(80, 65))
        self.toolButton_exit.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_exit.setFont(font)
        self.toolButton_exit.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_exit.setAutoFillBackground(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_exit.setIcon(icon5)
        self.toolButton_exit.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_exit.setAutoRepeatDelay(300)
        self.toolButton_exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_exit.setAutoRaise(False)
        self.toolButton_exit.setObjectName(_fromUtf8("toolButton_exit"))
        self.horizontalLayout_2.addWidget(self.toolButton_exit)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 1000, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtGui.QFrame.Raised)
        self.line_2.setLineWidth(4)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(15, 150, 970, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 5, 281, 25))
        self.label_3.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(460, 5, 455, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.groupBox.setFont(font)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButton_sp = QtGui.QRadioButton(self.groupBox)
        self.radioButton_sp.setGeometry(QtCore.QRect(1, 30, 45, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_sp.setFont(font)
        self.radioButton_sp.setChecked(True)
        self.radioButton_sp.setObjectName(_fromUtf8("radioButton_sp"))
        self.radioButton_r1 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_r1.setGeometry(QtCore.QRect(64, 30, 35, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_r1.setFont(font)
        self.radioButton_r1.setChecked(False)
        self.radioButton_r1.setObjectName(_fromUtf8("radioButton_r1"))
        self.radioButton_r2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_r2.setGeometry(QtCore.QRect(120, 30, 46, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_r2.setFont(font)
        self.radioButton_r2.setObjectName(_fromUtf8("radioButton_r2"))
        self.radioButton_pvs = QtGui.QRadioButton(self.groupBox)
        self.radioButton_pvs.setGeometry(QtCore.QRect(180, 30, 53, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_pvs.setFont(font)
        self.radioButton_pvs.setCheckable(True)
        self.radioButton_pvs.setObjectName(_fromUtf8("radioButton_pvs"))
        self.radioButton_sd = QtGui.QRadioButton(self.groupBox)
        self.radioButton_sd.setGeometry(QtCore.QRect(318, 30, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_sd.setFont(font)
        self.radioButton_sd.setCheckable(True)
        self.radioButton_sd.setObjectName(_fromUtf8("radioButton_sd"))
        self.radioButton_rmse = QtGui.QRadioButton(self.groupBox)
        self.radioButton_rmse.setGeometry(QtCore.QRect(380, 30, 71, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_rmse.setFont(font)
        self.radioButton_rmse.setCheckable(True)
        self.radioButton_rmse.setObjectName(_fromUtf8("radioButton_rmse"))
        self.radioButton_pvp = QtGui.QRadioButton(self.groupBox)
        self.radioButton_pvp.setGeometry(QtCore.QRect(240, 30, 55, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.radioButton_pvp.setFont(font)
        self.radioButton_pvp.setCheckable(True)
        self.radioButton_pvp.setObjectName(_fromUtf8("radioButton_pvp"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(330, 5, 101, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_dataBase = QtGui.QComboBox(self.frame)
        self.comboBox_dataBase.setGeometry(QtCore.QRect(330, 30, 101, 30))
        self.comboBox_dataBase.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_dataBase.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.comboBox_dataBase.setFont(font)
        self.comboBox_dataBase.setObjectName(_fromUtf8("comboBox_dataBase"))
        self.comboBox_distCol = QtGui.QComboBox(self.frame)
        self.comboBox_distCol.setGeometry(QtCore.QRect(10, 30, 211, 30))
        self.comboBox_distCol.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_distCol.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.comboBox_distCol.setFont(font)
        self.comboBox_distCol.setObjectName(_fromUtf8("comboBox_distCol"))
        self.plainTextEdit_modelo = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit_modelo.setEnabled(True)
        self.plainTextEdit_modelo.setGeometry(QtCore.QRect(10, 92, 641, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plainTextEdit_modelo.setFont(font)
        self.plainTextEdit_modelo.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";\n"
""))
        self.plainTextEdit_modelo.setReadOnly(True)
        self.plainTextEdit_modelo.setPlainText(_fromUtf8(""))
        self.plainTextEdit_modelo.setObjectName(_fromUtf8("plainTextEdit_modelo"))
        self.pushButton_adiciona = QtGui.QPushButton(self.frame)
        self.pushButton_adiciona.setGeometry(QtCore.QRect(662, 130, 61, 42))
        self.pushButton_adiciona.setAccessibleName(_fromUtf8(""))
        self.pushButton_adiciona.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/setaCircular.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_adiciona.setIcon(icon6)
        self.pushButton_adiciona.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_adiciona.setObjectName(_fromUtf8("pushButton_adiciona"))
        self.label_coef_3 = QtGui.QLabel(self.frame)
        self.label_coef_3.setGeometry(QtCore.QRect(10, 72, 361, 20))
        self.label_coef_3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_coef_3.setFont(font)
        self.label_coef_3.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_coef_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_coef_3.setIndent(3)
        self.label_coef_3.setObjectName(_fromUtf8("label_coef_3"))
        self.label_coef_4 = QtGui.QLabel(self.frame)
        self.label_coef_4.setGeometry(QtCore.QRect(734, 73, 185, 17))
        self.label_coef_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_coef_4.setFont(font)
        self.label_coef_4.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_coef_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_coef_4.setIndent(3)
        self.label_coef_4.setObjectName(_fromUtf8("label_coef_4"))
        self.listView_modelo = QtGui.QListView(self.frame)
        self.listView_modelo.setGeometry(QtCore.QRect(733, 90, 185, 105))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.listView_modelo.setFont(font)
        self.listView_modelo.setObjectName(_fromUtf8("listView_modelo"))
        self.pushButton_deleta = QtGui.QPushButton(self.frame)
        self.pushButton_deleta.setGeometry(QtCore.QRect(928, 135, 31, 31))
        self.pushButton_deleta.setAccessibleName(_fromUtf8(""))
        self.pushButton_deleta.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/deletar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_deleta.setIcon(icon7)
        self.pushButton_deleta.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_deleta.setObjectName(_fromUtf8("pushButton_deleta"))
        self.label_nomeModelo = QtGui.QLabel(self.frame)
        self.label_nomeModelo.setGeometry(QtCore.QRect(370, 72, 281, 20))
        self.label_nomeModelo.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_nomeModelo.setFont(font)
        self.label_nomeModelo.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);\n"
"color: rgb(64, 98, 181);"))
        self.label_nomeModelo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nomeModelo.setIndent(3)
        self.label_nomeModelo.setObjectName(_fromUtf8("label_nomeModelo"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(730, 192, 185, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_tuned = QtGui.QLabel(self.frame)
        self.label_tuned.setGeometry(QtCore.QRect(280, 56, 55, 55))
        self.label_tuned.setText(_fromUtf8(""))
        self.label_tuned.setPixmap(QtGui.QPixmap(_fromUtf8("img/tuned.png")))
        self.label_tuned.setScaledContents(True)
        self.label_tuned.setWordWrap(False)
        self.label_tuned.setObjectName(_fromUtf8("label_tuned"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(15, 90, 970, 55))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(601, 10, 81, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(494, 10, 95, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_afinidade = QtGui.QLabel(self.frame_3)
        self.label_afinidade.setGeometry(QtCore.QRect(494, 30, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_afinidade.setFont(font)
        self.label_afinidade.setStyleSheet(_fromUtf8(""))
        self.label_afinidade.setWordWrap(True)
        self.label_afinidade.setObjectName(_fromUtf8("label_afinidade"))
        self.label_quantia = QtGui.QLabel(self.frame_3)
        self.label_quantia.setGeometry(QtCore.QRect(604, 30, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_quantia.setFont(font)
        self.label_quantia.setStyleSheet(_fromUtf8(""))
        self.label_quantia.setWordWrap(True)
        self.label_quantia.setObjectName(_fromUtf8("label_quantia"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 171, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setBaseSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_system = QtGui.QLabel(self.frame_3)
        self.label_system.setGeometry(QtCore.QRect(20, 30, 331, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_system.setFont(font)
        self.label_system.setStyleSheet(_fromUtf8(""))
        self.label_system.setWordWrap(True)
        self.label_system.setObjectName(_fromUtf8("label_system"))
        self.label_tipoMedia = QtGui.QLabel(self.frame_3)
        self.label_tipoMedia.setGeometry(QtCore.QRect(380, 30, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_tipoMedia.setFont(font)
        self.label_tipoMedia.setStyleSheet(_fromUtf8(""))
        self.label_tipoMedia.setWordWrap(True)
        self.label_tipoMedia.setObjectName(_fromUtf8("label_tipoMedia"))
        self.label_experimento_3 = QtGui.QLabel(self.frame_3)
        self.label_experimento_3.setGeometry(QtCore.QRect(380, 10, 101, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_experimento_3.sizePolicy().hasHeightForWidth())
        self.label_experimento_3.setSizePolicy(sizePolicy)
        self.label_experimento_3.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_experimento_3.setFont(font)
        self.label_experimento_3.setWordWrap(True)
        self.label_experimento_3.setObjectName(_fromUtf8("label_experimento_3"))
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(840, 10, 120, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_estruturaInicial = QtGui.QLabel(self.frame_3)
        self.label_estruturaInicial.setGeometry(QtCore.QRect(705, 30, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_estruturaInicial.setFont(font)
        self.label_estruturaInicial.setStyleSheet(_fromUtf8(""))
        self.label_estruturaInicial.setObjectName(_fromUtf8("label_estruturaInicial"))
        self.label_17 = QtGui.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(705, 10, 122, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_outliers = QtGui.QLabel(self.frame_3)
        self.label_outliers.setGeometry(QtCore.QRect(840, 30, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_outliers.setFont(font)
        self.label_outliers.setStyleSheet(_fromUtf8(""))
        self.label_outliers.setObjectName(_fromUtf8("label_outliers"))
        self.label_26 = QtGui.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(260, 20, 67, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(15, 367, 970, 241))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_18 = QtGui.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(10, 122, 171, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("color: rgb(27, 107, 11);"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(9, 187, 240, 23))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setIndent(3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(330, 139, 321, 23))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setIndent(3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_pValueSpearmanTeste = QtGui.QLabel(self.frame_2)
        self.label_pValueSpearmanTeste.setGeometry(QtCore.QRect(651, 162, 309, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_pValueSpearmanTeste.sizePolicy().hasHeightForWidth())
        self.label_pValueSpearmanTeste.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_pValueSpearmanTeste.setFont(font)
        self.label_pValueSpearmanTeste.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_pValueSpearmanTeste.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pValueSpearmanTeste.setIndent(3)
        self.label_pValueSpearmanTeste.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_pValueSpearmanTeste.setObjectName(_fromUtf8("label_pValueSpearmanTeste"))
        self.label_setaSC = QtGui.QLabel(self.frame_2)
        self.label_setaSC.setEnabled(True)
        self.label_setaSC.setGeometry(QtCore.QRect(301, 162, 22, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_setaSC.sizePolicy().hasHeightForWidth())
        self.label_setaSC.setSizePolicy(sizePolicy)
        self.label_setaSC.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaSC.setFont(font)
        self.label_setaSC.setToolTip(_fromUtf8(""))
        self.label_setaSC.setText(_fromUtf8(""))
        self.label_setaSC.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaSC.setScaledContents(True)
        self.label_setaSC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaSC.setWordWrap(True)
        self.label_setaSC.setIndent(0)
        self.label_setaSC.setObjectName(_fromUtf8("label_setaSC"))
        self.label_pValuePerson = QtGui.QLabel(self.frame_2)
        self.label_pValuePerson.setGeometry(QtCore.QRect(9, 210, 240, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_pValuePerson.sizePolicy().hasHeightForWidth())
        self.label_pValuePerson.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_pValuePerson.setFont(font)
        self.label_pValuePerson.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_pValuePerson.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pValuePerson.setIndent(3)
        self.label_pValuePerson.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_pValuePerson.setObjectName(_fromUtf8("label_pValuePerson"))
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(9, 139, 322, 23))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setIndent(3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_setaPC = QtGui.QLabel(self.frame_2)
        self.label_setaPC.setEnabled(True)
        self.label_setaPC.setGeometry(QtCore.QRect(620, 162, 22, 25))
        self.label_setaPC.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPC.setFont(font)
        self.label_setaPC.setToolTip(_fromUtf8(""))
        self.label_setaPC.setText(_fromUtf8(""))
        self.label_setaPC.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPC.setScaledContents(True)
        self.label_setaPC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPC.setWordWrap(True)
        self.label_setaPC.setObjectName(_fromUtf8("label_setaPC"))
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(651, 139, 309, 23))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setIndent(3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_setaPVS = QtGui.QLabel(self.frame_2)
        self.label_setaPVS.setEnabled(True)
        self.label_setaPVS.setGeometry(QtCore.QRect(930, 162, 22, 25))
        self.label_setaPVS.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPVS.setFont(font)
        self.label_setaPVS.setToolTip(_fromUtf8(""))
        self.label_setaPVS.setText(_fromUtf8(""))
        self.label_setaPVS.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPVS.setScaledContents(True)
        self.label_setaPVS.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPVS.setWordWrap(True)
        self.label_setaPVS.setObjectName(_fromUtf8("label_setaPVS"))
        self.label_RTeste = QtGui.QLabel(self.frame_2)
        self.label_RTeste.setGeometry(QtCore.QRect(330, 162, 321, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_RTeste.sizePolicy().hasHeightForWidth())
        self.label_RTeste.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_RTeste.setFont(font)
        self.label_RTeste.setStyleSheet(_fromUtf8("background-color: rgb(200, 200,175);"))
        self.label_RTeste.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RTeste.setIndent(3)
        self.label_RTeste.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_RTeste.setObjectName(_fromUtf8("label_RTeste"))
        self.label_R2Teste = QtGui.QLabel(self.frame_2)
        self.label_R2Teste.setGeometry(QtCore.QRect(249, 210, 240, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_R2Teste.sizePolicy().hasHeightForWidth())
        self.label_R2Teste.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_R2Teste.setFont(font)
        self.label_R2Teste.setStyleSheet(_fromUtf8("background-color: rgb(200, 200,175);"))
        self.label_R2Teste.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_R2Teste.setIndent(3)
        self.label_R2Teste.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_R2Teste.setObjectName(_fromUtf8("label_R2Teste"))
        self.label_bestSpearmanTeste = QtGui.QLabel(self.frame_2)
        self.label_bestSpearmanTeste.setGeometry(QtCore.QRect(9, 162, 322, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_bestSpearmanTeste.sizePolicy().hasHeightForWidth())
        self.label_bestSpearmanTeste.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_bestSpearmanTeste.setFont(font)
        self.label_bestSpearmanTeste.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_bestSpearmanTeste.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_bestSpearmanTeste.setIndent(3)
        self.label_bestSpearmanTeste.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_bestSpearmanTeste.setObjectName(_fromUtf8("label_bestSpearmanTeste"))
        self.label_setaPVP = QtGui.QLabel(self.frame_2)
        self.label_setaPVP.setEnabled(True)
        self.label_setaPVP.setGeometry(QtCore.QRect(220, 210, 22, 25))
        self.label_setaPVP.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPVP.setFont(font)
        self.label_setaPVP.setToolTip(_fromUtf8(""))
        self.label_setaPVP.setText(_fromUtf8(""))
        self.label_setaPVP.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPVP.setScaledContents(True)
        self.label_setaPVP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPVP.setWordWrap(True)
        self.label_setaPVP.setObjectName(_fromUtf8("label_setaPVP"))
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(249, 187, 240, 23))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setIndent(3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_rmse = QtGui.QLabel(self.frame_2)
        self.label_rmse.setGeometry(QtCore.QRect(490, 210, 242, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_rmse.sizePolicy().hasHeightForWidth())
        self.label_rmse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_rmse.setFont(font)
        self.label_rmse.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_rmse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rmse.setIndent(3)
        self.label_rmse.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_rmse.setObjectName(_fromUtf8("label_rmse"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(489, 187, 240, 23))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(729, 187, 232, 23))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_stdDev = QtGui.QLabel(self.frame_2)
        self.label_stdDev.setGeometry(QtCore.QRect(729, 210, 232, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_stdDev.sizePolicy().hasHeightForWidth())
        self.label_stdDev.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_stdDev.setFont(font)
        self.label_stdDev.setStyleSheet(_fromUtf8("background-color: rgb(200, 200,175);"))
        self.label_stdDev.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_stdDev.setIndent(3)
        self.label_stdDev.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_stdDev.setObjectName(_fromUtf8("label_stdDev"))
        self.label_20 = QtGui.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(9, 7, 191, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet(_fromUtf8("color: rgb(0, 0, 214);"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_RTreino = QtGui.QLabel(self.frame_2)
        self.label_RTreino.setGeometry(QtCore.QRect(330, 47, 321, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_RTreino.sizePolicy().hasHeightForWidth())
        self.label_RTreino.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_RTreino.setFont(font)
        self.label_RTreino.setStyleSheet(_fromUtf8("background-color: rgb(200, 200,175);"))
        self.label_RTreino.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RTreino.setIndent(3)
        self.label_RTreino.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_RTreino.setObjectName(_fromUtf8("label_RTreino"))
        self.label_bestSpearmanTreino = QtGui.QLabel(self.frame_2)
        self.label_bestSpearmanTreino.setGeometry(QtCore.QRect(9, 47, 322, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_bestSpearmanTreino.sizePolicy().hasHeightForWidth())
        self.label_bestSpearmanTreino.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_bestSpearmanTreino.setFont(font)
        self.label_bestSpearmanTreino.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);\n"
""))
        self.label_bestSpearmanTreino.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_bestSpearmanTreino.setIndent(3)
        self.label_bestSpearmanTreino.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_bestSpearmanTreino.setObjectName(_fromUtf8("label_bestSpearmanTreino"))
        self.label_21 = QtGui.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(330, 24, 321, 23))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setIndent(3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(9, 24, 322, 23))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setIndent(3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(651, 24, 309, 23))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setIndent(3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_pValueSpearmanTreino = QtGui.QLabel(self.frame_2)
        self.label_pValueSpearmanTreino.setGeometry(QtCore.QRect(651, 47, 309, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_pValueSpearmanTreino.sizePolicy().hasHeightForWidth())
        self.label_pValueSpearmanTreino.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_pValueSpearmanTreino.setFont(font)
        self.label_pValueSpearmanTreino.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);\n"
""))
        self.label_pValueSpearmanTreino.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pValueSpearmanTreino.setIndent(3)
        self.label_pValueSpearmanTreino.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_pValueSpearmanTreino.setObjectName(_fromUtf8("label_pValueSpearmanTreino"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(730, 71, 232, 23))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setIndent(3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_19 = QtGui.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(249, 71, 240, 23))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setIndent(3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_R2Treino = QtGui.QLabel(self.frame_2)
        self.label_R2Treino.setGeometry(QtCore.QRect(249, 94, 240, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_R2Treino.sizePolicy().hasHeightForWidth())
        self.label_R2Treino.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_R2Treino.setFont(font)
        self.label_R2Treino.setStyleSheet(_fromUtf8("background-color: rgb(200, 200,175);"))
        self.label_R2Treino.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_R2Treino.setIndent(3)
        self.label_R2Treino.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_R2Treino.setObjectName(_fromUtf8("label_R2Treino"))
        self.label_rmseTreino = QtGui.QLabel(self.frame_2)
        self.label_rmseTreino.setGeometry(QtCore.QRect(489, 94, 242, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_rmseTreino.sizePolicy().hasHeightForWidth())
        self.label_rmseTreino.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_rmseTreino.setFont(font)
        self.label_rmseTreino.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_rmseTreino.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rmseTreino.setIndent(3)
        self.label_rmseTreino.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_rmseTreino.setObjectName(_fromUtf8("label_rmseTreino"))
        self.label_24 = QtGui.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(9, 71, 240, 23))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setIndent(3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_pValuePersonTreino = QtGui.QLabel(self.frame_2)
        self.label_pValuePersonTreino.setGeometry(QtCore.QRect(9, 94, 240, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_pValuePersonTreino.sizePolicy().hasHeightForWidth())
        self.label_pValuePersonTreino.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_pValuePersonTreino.setFont(font)
        self.label_pValuePersonTreino.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_pValuePersonTreino.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pValuePersonTreino.setIndent(3)
        self.label_pValuePersonTreino.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_pValuePersonTreino.setObjectName(_fromUtf8("label_pValuePersonTreino"))
        self.label_25 = QtGui.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(489, 71, 242, 23))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setIndent(3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_stdDevTreino = QtGui.QLabel(self.frame_2)
        self.label_stdDevTreino.setGeometry(QtCore.QRect(730, 94, 232, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_stdDevTreino.sizePolicy().hasHeightForWidth())
        self.label_stdDevTreino.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_stdDevTreino.setFont(font)
        self.label_stdDevTreino.setStyleSheet(_fromUtf8("background-color: rgb(200, 200,175);"))
        self.label_stdDevTreino.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_stdDevTreino.setIndent(3)
        self.label_stdDevTreino.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_stdDevTreino.setObjectName(_fromUtf8("label_stdDevTreino"))
        self.label_setaSCTreino = QtGui.QLabel(self.frame_2)
        self.label_setaSCTreino.setEnabled(True)
        self.label_setaSCTreino.setGeometry(QtCore.QRect(300, 47, 22, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_setaSCTreino.sizePolicy().hasHeightForWidth())
        self.label_setaSCTreino.setSizePolicy(sizePolicy)
        self.label_setaSCTreino.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaSCTreino.setFont(font)
        self.label_setaSCTreino.setToolTip(_fromUtf8(""))
        self.label_setaSCTreino.setText(_fromUtf8(""))
        self.label_setaSCTreino.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaSCTreino.setScaledContents(True)
        self.label_setaSCTreino.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaSCTreino.setWordWrap(True)
        self.label_setaSCTreino.setIndent(0)
        self.label_setaSCTreino.setObjectName(_fromUtf8("label_setaSCTreino"))
        self.label_setaPCTreino = QtGui.QLabel(self.frame_2)
        self.label_setaPCTreino.setEnabled(True)
        self.label_setaPCTreino.setGeometry(QtCore.QRect(620, 47, 22, 25))
        self.label_setaPCTreino.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPCTreino.setFont(font)
        self.label_setaPCTreino.setToolTip(_fromUtf8(""))
        self.label_setaPCTreino.setText(_fromUtf8(""))
        self.label_setaPCTreino.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPCTreino.setScaledContents(True)
        self.label_setaPCTreino.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPCTreino.setWordWrap(True)
        self.label_setaPCTreino.setObjectName(_fromUtf8("label_setaPCTreino"))
        self.label_setaPVPTreino = QtGui.QLabel(self.frame_2)
        self.label_setaPVPTreino.setEnabled(True)
        self.label_setaPVPTreino.setGeometry(QtCore.QRect(220, 94, 22, 25))
        self.label_setaPVPTreino.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPVPTreino.setFont(font)
        self.label_setaPVPTreino.setToolTip(_fromUtf8(""))
        self.label_setaPVPTreino.setText(_fromUtf8(""))
        self.label_setaPVPTreino.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPVPTreino.setScaledContents(True)
        self.label_setaPVPTreino.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPVPTreino.setWordWrap(True)
        self.label_setaPVPTreino.setObjectName(_fromUtf8("label_setaPVPTreino"))
        self.label_setaPVSTreino = QtGui.QLabel(self.frame_2)
        self.label_setaPVSTreino.setEnabled(True)
        self.label_setaPVSTreino.setGeometry(QtCore.QRect(930, 47, 22, 25))
        self.label_setaPVSTreino.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPVSTreino.setFont(font)
        self.label_setaPVSTreino.setToolTip(_fromUtf8(""))
        self.label_setaPVSTreino.setText(_fromUtf8(""))
        self.label_setaPVSTreino.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPVSTreino.setScaledContents(True)
        self.label_setaPVSTreino.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPVSTreino.setWordWrap(True)
        self.label_setaPVSTreino.setObjectName(_fromUtf8("label_setaPVSTreino"))
        self.label_18.raise_()
        self.label_15.raise_()
        self.label_12.raise_()
        self.label_pValueSpearmanTeste.raise_()
        self.label_pValuePerson.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_RTeste.raise_()
        self.label_R2Teste.raise_()
        self.label_bestSpearmanTeste.raise_()
        self.label_16.raise_()
        self.label_setaSC.raise_()
        self.label_setaPVS.raise_()
        self.label_setaPC.raise_()
        self.label_setaPVP.raise_()
        self.label_rmse.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_stdDev.raise_()
        self.label_20.raise_()
        self.label_RTreino.raise_()
        self.label_bestSpearmanTreino.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_pValueSpearmanTreino.raise_()
        self.label_6.raise_()
        self.label_19.raise_()
        self.label_R2Treino.raise_()
        self.label_rmseTreino.raise_()
        self.label_24.raise_()
        self.label_pValuePersonTreino.raise_()
        self.label_25.raise_()
        self.label_stdDevTreino.raise_()
        self.label_setaSCTreino.raise_()
        self.label_setaPCTreino.raise_()
        self.label_setaPVPTreino.raise_()
        self.label_setaPVSTreino.raise_()
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(15, 609, 601, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 251, 202);"))
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 571, 15))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setToolTip(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 90, 65))
        self.label_27.setMaximumSize(QtCore.QSize(90, 65))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("img/TabaComLetras.png")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.frame.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.line_2.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame_4.raise_()
        self.label_27.raise_()
        MainWindow_correlacao.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_correlacao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow_correlacao.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_correlacao)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_correlacao.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_correlacao)
        QtCore.QObject.connect(self.toolButton_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.sair)
        QtCore.QObject.connect(self.toolButton_iniciar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.iniciarCorrelacao)
        QtCore.QObject.connect(self.toolButton_outlier, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.retiraOutliers)
        QtCore.QObject.connect(self.pushButton_deleta, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.deletaModelo)
        QtCore.QObject.connect(self.pushButton_adiciona, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.salvaModelo)
        QtCore.QObject.connect(self.listView_modelo, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), MainWindow_correlacao.selecionaModelo)
        QtCore.QObject.connect(self.radioButton_sp, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.radioButton_r1, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.radioButton_r2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.radioButton_pvs, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.radioButton_pvp, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.radioButton_sd, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.radioButton_rmse, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.comboBox_distCol, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.comboBox_dataBase, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow_correlacao.limpaModelo)
        QtCore.QObject.connect(self.toolButton_graficos, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.geraGraficos)
        QtCore.QObject.connect(self.listView_modelo, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), MainWindow_correlacao.mostraModelo)
        QtCore.QObject.connect(self.toolButton_tuning, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_correlacao.ajustaModelo)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_correlacao)

    def retranslateUi(self, MainWindow_correlacao):
        MainWindow_correlacao.setWindowTitle(_translate("MainWindow_correlacao", "Statistical Analysis of the Machine Learning Models", None))
        MainWindow_correlacao.setStatusTip(_translate("MainWindow_correlacao", "Performing Statistical Analysis of the Machine-Learning Models", None))
        MainWindow_correlacao.setWhatsThis(_translate("MainWindow_correlacao", "Do Correlation", None))
        MainWindow_correlacao.setAccessibleName(_translate("MainWindow_correlacao", "Correlation", None))
        MainWindow_correlacao.setAccessibleDescription(_translate("MainWindow_correlacao", "Do Correlation", None))
        self.toolButton_iniciar.setToolTip(_translate("MainWindow_correlacao", "<html><head/><body><p>Calculates correlation in test set and trining set.</p></body></html>", None))
        self.toolButton_iniciar.setStatusTip(_translate("MainWindow_correlacao", "Downloading", None))
        self.toolButton_iniciar.setWhatsThis(_translate("MainWindow_correlacao", "Start experiment", None))
        self.toolButton_iniciar.setAccessibleName(_translate("MainWindow_correlacao", "start", None))
        self.toolButton_iniciar.setText(_translate("MainWindow_correlacao", "&Start", None))
        self.toolButton_tuning.setToolTip(_translate("MainWindow_correlacao", "Fine tuning to a model", None))
        self.toolButton_tuning.setStatusTip(_translate("MainWindow_correlacao", "Fine tuning to a model", None))
        self.toolButton_tuning.setWhatsThis(_translate("MainWindow_correlacao", "Fine tuning to a model", None))
        self.toolButton_tuning.setAccessibleName(_translate("MainWindow_correlacao", "Tuning", None))
        self.toolButton_tuning.setAccessibleDescription(_translate("MainWindow_correlacao", "Fine tuning to a model", None))
        self.toolButton_tuning.setText(_translate("MainWindow_correlacao", "&Tuning", None))
        self.toolButton_graficos.setToolTip(_translate("MainWindow_correlacao", "Generate plots", None))
        self.toolButton_graficos.setStatusTip(_translate("MainWindow_correlacao", "Generate plots", None))
        self.toolButton_graficos.setWhatsThis(_translate("MainWindow_correlacao", "Generate plots", None))
        self.toolButton_graficos.setAccessibleName(_translate("MainWindow_correlacao", "Plots", None))
        self.toolButton_graficos.setText(_translate("MainWindow_correlacao", "&Plots", None))
        self.toolButton_outlier.setToolTip(_translate("MainWindow_correlacao", "<html><head/><body><p>Remove outliers.</p><p>To use, press the start button first.</p><p>This is only possible if there is no outlier excluded.</p></body></html>", None))
        self.toolButton_outlier.setStatusTip(_translate("MainWindow_correlacao", "remove outliers", None))
        self.toolButton_outlier.setWhatsThis(_translate("MainWindow_correlacao", "remove outliers", None))
        self.toolButton_outlier.setAccessibleName(_translate("MainWindow_correlacao", "outliers", None))
        self.toolButton_outlier.setText(_translate("MainWindow_correlacao", "&Outliers", None))
        self.toolButton_exit.setToolTip(_translate("MainWindow_correlacao", "Exit Experiment", None))
        self.toolButton_exit.setStatusTip(_translate("MainWindow_correlacao", "Exit Experiment", None))
        self.toolButton_exit.setWhatsThis(_translate("MainWindow_correlacao", "Exit", None))
        self.toolButton_exit.setAccessibleName(_translate("MainWindow_correlacao", "Exit", None))
        self.toolButton_exit.setText(_translate("MainWindow_correlacao", "&Exit", None))
        self.label_3.setToolTip(_translate("MainWindow_correlacao", "List of Generated Energy Terms Files", None))
        self.label_3.setText(_translate("MainWindow_correlacao", "List of Generated Energy Terms Files", None))
        self.groupBox.setToolTip(_translate("MainWindow_correlacao", "<html><head/><body><p>Coefficient to compare best equation</p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindow_correlacao", "Coefficient to compare", None))
        self.radioButton_sp.setToolTip(_translate("MainWindow_correlacao", "Spearman", None))
        self.radioButton_sp.setStatusTip(_translate("MainWindow_correlacao", "Spearman", None))
        self.radioButton_sp.setWhatsThis(_translate("MainWindow_correlacao", "Spearman", None))
        self.radioButton_sp.setText(_translate("MainWindow_correlacao", "SP", None))
        self.radioButton_r1.setToolTip(_translate("MainWindow_correlacao", "R", None))
        self.radioButton_r1.setStatusTip(_translate("MainWindow_correlacao", "R", None))
        self.radioButton_r1.setWhatsThis(_translate("MainWindow_correlacao", "R", None))
        self.radioButton_r1.setText(_translate("MainWindow_correlacao", "R", None))
        self.radioButton_r2.setToolTip(_translate("MainWindow_correlacao", "R2", None))
        self.radioButton_r2.setStatusTip(_translate("MainWindow_correlacao", "R2", None))
        self.radioButton_r2.setWhatsThis(_translate("MainWindow_correlacao", "R2", None))
        self.radioButton_r2.setText(_translate("MainWindow_correlacao", "R2", None))
        self.radioButton_pvs.setToolTip(_translate("MainWindow_correlacao", "p-value Spearman", None))
        self.radioButton_pvs.setStatusTip(_translate("MainWindow_correlacao", "p-value Spearman", None))
        self.radioButton_pvs.setWhatsThis(_translate("MainWindow_correlacao", "p-value Spearman", None))
        self.radioButton_pvs.setText(_translate("MainWindow_correlacao", "PVs", None))
        self.radioButton_sd.setToolTip(_translate("MainWindow_correlacao", "Standard Deviation", None))
        self.radioButton_sd.setStatusTip(_translate("MainWindow_correlacao", "Standard Deviation", None))
        self.radioButton_sd.setWhatsThis(_translate("MainWindow_correlacao", "Standard Deviation", None))
        self.radioButton_sd.setText(_translate("MainWindow_correlacao", "SD", None))
        self.radioButton_rmse.setToolTip(_translate("MainWindow_correlacao", "RMSE", None))
        self.radioButton_rmse.setStatusTip(_translate("MainWindow_correlacao", "RMSE", None))
        self.radioButton_rmse.setWhatsThis(_translate("MainWindow_correlacao", "RMSE", None))
        self.radioButton_rmse.setText(_translate("MainWindow_correlacao", "RMSE", None))
        self.radioButton_pvp.setToolTip(_translate("MainWindow_correlacao", "p-value Pearson", None))
        self.radioButton_pvp.setStatusTip(_translate("MainWindow_correlacao", "p-value Pearson", None))
        self.radioButton_pvp.setWhatsThis(_translate("MainWindow_correlacao", "p-value Pearson", None))
        self.radioButton_pvp.setText(_translate("MainWindow_correlacao", "PVp", None))
        self.label_5.setToolTip(_translate("MainWindow_correlacao", "Database where the information was obtained", None))
        self.label_5.setText(_translate("MainWindow_correlacao", "Data Base", None))
        self.comboBox_dataBase.setToolTip(_translate("MainWindow_correlacao", "Database where the information was obtained", None))
        self.comboBox_distCol.setToolTip(_translate("MainWindow_correlacao", "List of Generated Energy Terms Files", None))
        self.pushButton_adiciona.setToolTip(_translate("MainWindow_correlacao", "Add as a good model", None))
        self.pushButton_adiciona.setStatusTip(_translate("MainWindow_correlacao", "Add as a good model", None))
        self.pushButton_adiciona.setWhatsThis(_translate("MainWindow_correlacao", "Add as a good model", None))
        self.pushButton_adiciona.setAccessibleDescription(_translate("MainWindow_correlacao", "Add as a good model", None))
        self.label_coef_3.setText(_translate("MainWindow_correlacao", "<html><head/><body><p>Best Machine-Learning Model</p></body></html>", None))
        self.label_coef_4.setToolTip(_translate("MainWindow_correlacao", "Click on the model to show the description or to delete.", None))
        self.label_coef_4.setStatusTip(_translate("MainWindow_correlacao", "Click on the model to show the description or to delete.", None))
        self.label_coef_4.setWhatsThis(_translate("MainWindow_correlacao", "Click on the model to show the description or to delete.", None))
        self.label_coef_4.setText(_translate("MainWindow_correlacao", "Good Models", None))
        self.listView_modelo.setToolTip(_translate("MainWindow_correlacao", "Double click on the model to show or just select to delete.", None))
        self.listView_modelo.setStatusTip(_translate("MainWindow_correlacao", "Double click on the model to show or just select to delete.", None))
        self.listView_modelo.setWhatsThis(_translate("MainWindow_correlacao", "Double click on the model to show or just select to delete.", None))
        self.pushButton_deleta.setToolTip(_translate("MainWindow_correlacao", "Delete model selectd as good", None))
        self.pushButton_deleta.setStatusTip(_translate("MainWindow_correlacao", "Delete model selectd as good", None))
        self.pushButton_deleta.setWhatsThis(_translate("MainWindow_correlacao", "Delete model selectd as good", None))
        self.pushButton_deleta.setAccessibleDescription(_translate("MainWindow_correlacao", "Add as a good model", None))
        self.label_nomeModelo.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label.setText(_translate("MainWindow_correlacao", "*Double click to see the model detail.", None))
        self.label_tuned.setToolTip(_translate("MainWindow_correlacao", "Model fine tuning done", None))
        self.label_tuned.setStatusTip(_translate("MainWindow_correlacao", "Model fine tuning done", None))
        self.label_tuned.setWhatsThis(_translate("MainWindow_correlacao", "Model fine tuning done", None))
        self.label_tuned.setAccessibleName(_translate("MainWindow_correlacao", "Tuned", None))
        self.label_9.setToolTip(_translate("MainWindow_correlacao", "<html><head/><body><p>This is the value after the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_9.setText(_translate("MainWindow_correlacao", "Structures", None))
        self.label_10.setText(_translate("MainWindow_correlacao", "Affinity Type", None))
        self.label_afinidade.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_quantia.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow_correlacao", "Protein System Name", None))
        self.label_system.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_tipoMedia.setToolTip(_translate("MainWindow_correlacao", "Average Type", None))
        self.label_tipoMedia.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_experimento_3.setText(_translate("MainWindow_correlacao", "Average Type", None))
        self.label_11.setToolTip(_translate("MainWindow_correlacao", "<html><head/><body><p>If &quot;yes&quot;, the outliers have already been deleted</p></body></html>", None))
        self.label_11.setText(_translate("MainWindow_correlacao", "<html><head/><body><p>Deleted Outliers</p></body></html>", None))
        self.label_estruturaInicial.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_17.setToolTip(_translate("MainWindow_correlacao", "<html><head/><body><p>This is the value before the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_17.setText(_translate("MainWindow_correlacao", "Initial Structures", None))
        self.label_outliers.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_26.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_18.setText(_translate("MainWindow_correlacao", "Correlation Test Set ", None))
        self.label_15.setText(_translate("MainWindow_correlacao", "P Value for Pearson", None))
        self.label_12.setText(_translate("MainWindow_correlacao", "<html><head/><body><p>Pearson\'s Correlation (R)</p></body></html>", None))
        self.label_pValueSpearmanTeste.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_pValuePerson.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_13.setText(_translate("MainWindow_correlacao", "<html><head/><body><p>Spearman\'s Correlation</p></body></html>", None))
        self.label_14.setText(_translate("MainWindow_correlacao", "<html><head/><body><p>P Value for Spearman</p></body></html>", None))
        self.label_RTeste.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_R2Teste.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_bestSpearmanTeste.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_16.setText(_translate("MainWindow_correlacao", "R2", None))
        self.label_rmse.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_2.setText(_translate("MainWindow_correlacao", "RMSE", None))
        self.label_4.setText(_translate("MainWindow_correlacao", " Standard Deviation ", None))
        self.label_stdDev.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_20.setText(_translate("MainWindow_correlacao", "Correlation Training Set ", None))
        self.label_RTreino.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_bestSpearmanTreino.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_21.setText(_translate("MainWindow_correlacao", "<html><head/><body><p>Pearson\'s Correlation (R)</p></body></html>", None))
        self.label_22.setText(_translate("MainWindow_correlacao", "<html><head/><body><p>Spearman\'s Correlation</p></body></html>", None))
        self.label_23.setText(_translate("MainWindow_correlacao", "<html><head/><body><p>P Value for Spearman</p></body></html>", None))
        self.label_pValueSpearmanTreino.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_6.setText(_translate("MainWindow_correlacao", " Standard Deviation ", None))
        self.label_19.setText(_translate("MainWindow_correlacao", "R2", None))
        self.label_R2Treino.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_rmseTreino.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_24.setText(_translate("MainWindow_correlacao", "P Value for Pearson", None))
        self.label_pValuePersonTreino.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_25.setText(_translate("MainWindow_correlacao", "RMSE", None))
        self.label_stdDevTreino.setText(_translate("MainWindow_correlacao", "TextLabel", None))
        self.label_8.setText(_translate("MainWindow_correlacao", "<html><head/><body><p><span style=\" font-weight:600;\">Note: </span>Consider a good model if pv &lt; 5% and CC &gt; 50% and Best Spearman &gt; 60%</p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow_correlacao = QtGui.QMainWindow()
    ui = Ui_MainWindow_correlacao()
    ui.setupUi(MainWindow_correlacao)
    MainWindow_correlacao.show()
    sys.exit(app.exec_())

