# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceOutliers.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(600, 350)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        MainWindow.setFont(font)
        self.label = QtGui.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(20, 110, 531, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.frame_percent = QtGui.QFrame(MainWindow)
        self.frame_percent.setGeometry(QtCore.QRect(20, 140, 560, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_percent.setFont(font)
        self.frame_percent.setStyleSheet(_fromUtf8(""))
        self.frame_percent.setFrameShape(QtGui.QFrame.Box)
        self.frame_percent.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_percent.setLineWidth(2)
        self.frame_percent.setMidLineWidth(1)
        self.frame_percent.setObjectName(_fromUtf8("frame_percent"))
        self.horizontalSlider_percent = QtGui.QSlider(self.frame_percent)
        self.horizontalSlider_percent.setGeometry(QtCore.QRect(3, 15, 511, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalSlider_percent.setFont(font)
        self.horizontalSlider_percent.setStyleSheet(_fromUtf8(""))
        self.horizontalSlider_percent.setMaximum(40)
        self.horizontalSlider_percent.setSingleStep(1)
        self.horizontalSlider_percent.setProperty("value", 0)
        self.horizontalSlider_percent.setSliderPosition(0)
        self.horizontalSlider_percent.setTracking(True)
        self.horizontalSlider_percent.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_percent.setInvertedAppearance(False)
        self.horizontalSlider_percent.setInvertedControls(False)
        self.horizontalSlider_percent.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_percent.setTickInterval(1)
        self.horizontalSlider_percent.setObjectName(_fromUtf8("horizontalSlider_percent"))
        self.label_percent = QtGui.QLabel(self.frame_percent)
        self.label_percent.setGeometry(QtCore.QRect(520, 15, 31, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_percent.setFont(font)
        self.label_percent.setStyleSheet(_fromUtf8("color: rgb(32, 74, 135);"))
        self.label_percent.setObjectName(_fromUtf8("label_percent"))
        self.line = QtGui.QFrame(MainWindow)
        self.line.setGeometry(QtCore.QRect(0, 70, 600, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setLineWidth(4)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(MainWindow)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(90, 0, 611, 77))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(58)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_4.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_4.setMinimumSize(QtCore.QSize(0, 58))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalLayoutWidget_4.setFont(font)
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_iniciar = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_iniciar.sizePolicy().hasHeightForWidth())
        self.toolButton_iniciar.setSizePolicy(sizePolicy)
        self.toolButton_iniciar.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_iniciar.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.toolButton_iniciar.setFont(font)
        self.toolButton_iniciar.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_iniciar.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/iniciar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_iniciar.setIcon(icon)
        self.toolButton_iniciar.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_iniciar.setAutoRepeatDelay(300)
        self.toolButton_iniciar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_iniciar.setAutoRaise(False)
        self.toolButton_iniciar.setObjectName(_fromUtf8("toolButton_iniciar"))
        self.horizontalLayout_2.addWidget(self.toolButton_iniciar)
        self.toolButton_exit_2 = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_exit_2.sizePolicy().hasHeightForWidth())
        self.toolButton_exit_2.setSizePolicy(sizePolicy)
        self.toolButton_exit_2.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_exit_2.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.toolButton_exit_2.setFont(font)
        self.toolButton_exit_2.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_exit_2.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_exit_2.setIcon(icon1)
        self.toolButton_exit_2.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_exit_2.setAutoRepeatDelay(300)
        self.toolButton_exit_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_exit_2.setAutoRaise(False)
        self.toolButton_exit_2.setObjectName(_fromUtf8("toolButton_exit_2"))
        self.horizontalLayout_2.addWidget(self.toolButton_exit_2)
        self.frame_2 = QtGui.QFrame(MainWindow)
        self.frame_2.setGeometry(QtCore.QRect(100, 190, 361, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 237, 861, 77))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setIndent(3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_setaSC = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_setaSC.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_setaSC.sizePolicy().hasHeightForWidth())
        self.label_setaSC.setSizePolicy(sizePolicy)
        self.label_setaSC.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaSC.setFont(font)
        self.label_setaSC.setToolTip(_fromUtf8(""))
        self.label_setaSC.setText(_fromUtf8(""))
        self.label_setaSC.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaSC.setScaledContents(True)
        self.label_setaSC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaSC.setWordWrap(True)
        self.label_setaSC.setIndent(0)
        self.label_setaSC.setObjectName(_fromUtf8("label_setaSC"))
        self.gridLayout_3.addWidget(self.label_setaSC, 1, 1, 1, 1)
        self.label_setaPVP = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_setaPVP.setEnabled(True)
        self.label_setaPVP.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPVP.setFont(font)
        self.label_setaPVP.setToolTip(_fromUtf8(""))
        self.label_setaPVP.setText(_fromUtf8(""))
        self.label_setaPVP.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPVP.setScaledContents(True)
        self.label_setaPVP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPVP.setWordWrap(True)
        self.label_setaPVP.setObjectName(_fromUtf8("label_setaPVP"))
        self.gridLayout_3.addWidget(self.label_setaPVP, 1, 7, 1, 1)
        self.label_R2Teste = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_R2Teste.sizePolicy().hasHeightForWidth())
        self.label_R2Teste.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_R2Teste.setFont(font)
        self.label_R2Teste.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_R2Teste.setIndent(3)
        self.label_R2Teste.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_R2Teste.setObjectName(_fromUtf8("label_R2Teste"))
        self.gridLayout_3.addWidget(self.label_R2Teste, 1, 8, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setIndent(3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 6, 1, 1)
        self.label_coeficientCorrelationTeste = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_coeficientCorrelationTeste.sizePolicy().hasHeightForWidth())
        self.label_coeficientCorrelationTeste.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_coeficientCorrelationTeste.setFont(font)
        self.label_coeficientCorrelationTeste.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_coeficientCorrelationTeste.setIndent(3)
        self.label_coeficientCorrelationTeste.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_coeficientCorrelationTeste.setObjectName(_fromUtf8("label_coeficientCorrelationTeste"))
        self.gridLayout_3.addWidget(self.label_coeficientCorrelationTeste, 1, 2, 1, 1)
        self.label_pValuePerson = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_pValuePerson.sizePolicy().hasHeightForWidth())
        self.label_pValuePerson.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_pValuePerson.setFont(font)
        self.label_pValuePerson.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_pValuePerson.setIndent(3)
        self.label_pValuePerson.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_pValuePerson.setObjectName(_fromUtf8("label_pValuePerson"))
        self.gridLayout_3.addWidget(self.label_pValuePerson, 1, 6, 1, 1)
        self.label_pValueSpearman = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_pValueSpearman.sizePolicy().hasHeightForWidth())
        self.label_pValueSpearman.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_pValueSpearman.setFont(font)
        self.label_pValueSpearman.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_pValueSpearman.setIndent(3)
        self.label_pValueSpearman.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_pValueSpearman.setObjectName(_fromUtf8("label_pValueSpearman"))
        self.gridLayout_3.addWidget(self.label_pValueSpearman, 1, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setIndent(3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 8, 1, 1)
        self.label_setaPVS = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_setaPVS.setEnabled(True)
        self.label_setaPVS.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPVS.setFont(font)
        self.label_setaPVS.setToolTip(_fromUtf8(""))
        self.label_setaPVS.setText(_fromUtf8(""))
        self.label_setaPVS.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPVS.setScaledContents(True)
        self.label_setaPVS.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPVS.setWordWrap(True)
        self.label_setaPVS.setObjectName(_fromUtf8("label_setaPVS"))
        self.gridLayout_3.addWidget(self.label_setaPVS, 1, 5, 1, 1)
        self.label_setaPC = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_setaPC.setEnabled(True)
        self.label_setaPC.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaPC.setFont(font)
        self.label_setaPC.setToolTip(_fromUtf8(""))
        self.label_setaPC.setText(_fromUtf8(""))
        self.label_setaPC.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaPC.setScaledContents(True)
        self.label_setaPC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaPC.setWordWrap(True)
        self.label_setaPC.setObjectName(_fromUtf8("label_setaPC"))
        self.gridLayout_3.addWidget(self.label_setaPC, 1, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setIndent(3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_bestSpearmanTest = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_bestSpearmanTest.sizePolicy().hasHeightForWidth())
        self.label_bestSpearmanTest.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_bestSpearmanTest.setFont(font)
        self.label_bestSpearmanTest.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_bestSpearmanTest.setIndent(3)
        self.label_bestSpearmanTest.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_bestSpearmanTest.setObjectName(_fromUtf8("label_bestSpearmanTest"))
        self.gridLayout_3.addWidget(self.label_bestSpearmanTest, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setIndent(3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_setaVazia_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_setaVazia_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_setaVazia_2.sizePolicy().hasHeightForWidth())
        self.label_setaVazia_2.setSizePolicy(sizePolicy)
        self.label_setaVazia_2.setMaximumSize(QtCore.QSize(22, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_setaVazia_2.setFont(font)
        self.label_setaVazia_2.setToolTip(_fromUtf8(""))
        self.label_setaVazia_2.setText(_fromUtf8(""))
        self.label_setaVazia_2.setPixmap(QtGui.QPixmap(_fromUtf8("img/setaNula.png")))
        self.label_setaVazia_2.setScaledContents(True)
        self.label_setaVazia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setaVazia_2.setWordWrap(True)
        self.label_setaVazia_2.setIndent(0)
        self.label_setaVazia_2.setObjectName(_fromUtf8("label_setaVazia_2"))
        self.gridLayout_3.addWidget(self.label_setaVazia_2, 1, 9, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(20, 220, 171, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.toolButton_media = QtGui.QToolButton(self.frame_2)
        self.toolButton_media.setGeometry(QtCore.QRect(820, 20, 35, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.toolButton_media.sizePolicy().hasHeightForWidth())
        self.toolButton_media.setSizePolicy(sizePolicy)
        self.toolButton_media.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_media.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.toolButton_media.setFont(font)
        self.toolButton_media.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_media.setAutoFillBackground(False)
        self.toolButton_media.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/average.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_media.setIcon(icon2)
        self.toolButton_media.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_media.setAutoRepeatDelay(300)
        self.toolButton_media.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_media.setAutoRaise(False)
        self.toolButton_media.setObjectName(_fromUtf8("toolButton_media"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(15, 16, 331, 58))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_3.setIndent(10)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_inicial = QtGui.QLabel(self.gridLayoutWidget)
        self.label_inicial.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_inicial.setFont(font)
        self.label_inicial.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_inicial.setScaledContents(False)
        self.label_inicial.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_inicial.setIndent(10)
        self.label_inicial.setObjectName(_fromUtf8("label_inicial"))
        self.gridLayout.addWidget(self.label_inicial, 1, 0, 1, 1)
        self.label_final = QtGui.QLabel(self.gridLayoutWidget)
        self.label_final.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_final.setFont(font)
        self.label_final.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_final.setScaledContents(False)
        self.label_final.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_final.setIndent(10)
        self.label_final.setObjectName(_fromUtf8("label_final"))
        self.gridLayout.addWidget(self.label_final, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_2.setIndent(10)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(MainWindow)
        self.frame_4.setGeometry(QtCore.QRect(20, 300, 571, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 251, 202);"))
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(10, 7, 531, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setToolTip(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_27 = QtGui.QLabel(MainWindow)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 90, 65))
        self.label_27.setMaximumSize(QtCore.QSize(90, 65))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("img/TabaComLetras.png")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.toolButton_iniciar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.outliers)
        QtCore.QObject.connect(self.toolButton_exit_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sair)
        QtCore.QObject.connect(self.horizontalSlider_percent, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.atualizaSlider)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Exclude Outliers", None))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adjusting the deviation percentage of the distance from the average for the exclusion of outliers.</p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Set the distance out of the mean percentage to the outliers", None))
        self.horizontalSlider_percent.setToolTip(_translate("MainWindow", "<html><head/><body><p>Adjusting the deviation percentage of the distance from the average for the exclusion of outliers.</p></body></html>", None))
        self.label_percent.setText(_translate("MainWindow", "TextLabel", None))
        self.toolButton_iniciar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exclude Outliers</p></body></html>", None))
        self.toolButton_iniciar.setStatusTip(_translate("MainWindow", "Downloading", None))
        self.toolButton_iniciar.setWhatsThis(_translate("MainWindow", "Start experiment", None))
        self.toolButton_iniciar.setAccessibleName(_translate("MainWindow", "start", None))
        self.toolButton_iniciar.setText(_translate("MainWindow", "&Start", None))
        self.toolButton_exit_2.setToolTip(_translate("MainWindow", "Exit Experiment", None))
        self.toolButton_exit_2.setStatusTip(_translate("MainWindow", "Exit Experiment", None))
        self.toolButton_exit_2.setWhatsThis(_translate("MainWindow", "Exit", None))
        self.toolButton_exit_2.setAccessibleName(_translate("MainWindow", "Exit", None))
        self.toolButton_exit_2.setText(_translate("MainWindow", "&Exit", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Spearman\'s Correlation</p></body></html>", None))
        self.label_R2Teste.setText(_translate("MainWindow", "TextLabel", None))
        self.label_15.setText(_translate("MainWindow", "P Value for Pearson", None))
        self.label_coeficientCorrelationTeste.setText(_translate("MainWindow", "TextLabel", None))
        self.label_pValuePerson.setText(_translate("MainWindow", "TextLabel", None))
        self.label_pValueSpearman.setText(_translate("MainWindow", "TextLabel", None))
        self.label_16.setText(_translate("MainWindow", "R2", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>P Value for Spearman</p></body></html>", None))
        self.label_bestSpearmanTest.setText(_translate("MainWindow", "TextLabel", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Pearson\'s Correlation (R)</p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "Correlation Test Set ", None))
        self.toolButton_media.setToolTip(_translate("MainWindow", "Show average distance", None))
        self.toolButton_media.setStatusTip(_translate("MainWindow", "distance", None))
        self.toolButton_media.setWhatsThis(_translate("MainWindow", "distance", None))
        self.toolButton_media.setAccessibleName(_translate("MainWindow", "distance", None))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the value after the outliers are deleted.</p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "Final structure size", None))
        self.label_inicial.setText(_translate("MainWindow", "TextLabel", None))
        self.label_final.setText(_translate("MainWindow", "TextLabel", None))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the value before the outliers are deleted.</p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Initial structure size", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Note: </span>The exclusion of outliers is based on experimental values.</p><p><br/></p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

