# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceRegressao.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_regressao(object):
    def setupUi(self, MainWindow_regressao):
        MainWindow_regressao.setObjectName(_fromUtf8("MainWindow_regressao"))
        MainWindow_regressao.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow_regressao.resize(900, 600)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        MainWindow_regressao.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/beagle3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_regressao.setWindowIcon(icon)
        MainWindow_regressao.setToolTip(_fromUtf8(""))
        MainWindow_regressao.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow_regressao)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(90, 0, 801, 77))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalLayoutWidget_4.setFont(font)
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_iniciar = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_iniciar.sizePolicy().hasHeightForWidth())
        self.toolButton_iniciar.setSizePolicy(sizePolicy)
        self.toolButton_iniciar.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_iniciar.setMaximumSize(QtCore.QSize(85, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_iniciar.setFont(font)
        self.toolButton_iniciar.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_iniciar.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/iniciar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_iniciar.setIcon(icon1)
        self.toolButton_iniciar.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_iniciar.setAutoRepeatDelay(300)
        self.toolButton_iniciar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_iniciar.setAutoRaise(False)
        self.toolButton_iniciar.setObjectName(_fromUtf8("toolButton_iniciar"))
        self.horizontalLayout_2.addWidget(self.toolButton_iniciar)
        self.toolButton_exit = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_exit.sizePolicy().hasHeightForWidth())
        self.toolButton_exit.setSizePolicy(sizePolicy)
        self.toolButton_exit.setMinimumSize(QtCore.QSize(52, 65))
        self.toolButton_exit.setMaximumSize(QtCore.QSize(85, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.toolButton_exit.setFont(font)
        self.toolButton_exit.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_exit.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_exit.setIcon(icon2)
        self.toolButton_exit.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_exit.setAutoRepeatDelay(300)
        self.toolButton_exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_exit.setAutoRaise(False)
        self.toolButton_exit.setObjectName(_fromUtf8("toolButton_exit"))
        self.horizontalLayout_2.addWidget(self.toolButton_exit)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 900, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtGui.QFrame.Raised)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(15, 188, 870, 251))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.comboBox_variaveis = QtGui.QComboBox(self.frame)
        self.comboBox_variaveis.setGeometry(QtCore.QRect(30, 120, 60, 30))
        self.comboBox_variaveis.setMinimumSize(QtCore.QSize(60, 30))
        self.comboBox_variaveis.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.comboBox_variaveis.setFont(font)
        self.comboBox_variaveis.setObjectName(_fromUtf8("comboBox_variaveis"))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.comboBox_variaveis.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 161, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox_dataBase = QtGui.QComboBox(self.frame)
        self.comboBox_dataBase.setGeometry(QtCore.QRect(30, 200, 121, 30))
        self.comboBox_dataBase.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_dataBase.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.comboBox_dataBase.setFont(font)
        self.comboBox_dataBase.setObjectName(_fromUtf8("comboBox_dataBase"))
        self.comboBox_dataBase.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 91, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_distance = QtGui.QComboBox(self.frame)
        self.comboBox_distance.setGeometry(QtCore.QRect(30, 40, 61, 30))
        self.comboBox_distance.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_distance.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.comboBox_distance.setFont(font)
        self.comboBox_distance.setObjectName(_fromUtf8("comboBox_distance"))
        self.comboBox_distance.addItem(_fromUtf8(""))
        self.label_distancia = QtGui.QLabel(self.frame)
        self.label_distancia.setGeometry(QtCore.QRect(30, 10, 161, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_distancia.setFont(font)
        self.label_distancia.setObjectName(_fromUtf8("label_distancia"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 10, 221, 231))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.checkBox_rl = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_rl.setGeometry(QtCore.QRect(30, 30, 146, 23))
        self.checkBox_rl.setObjectName(_fromUtf8("checkBox_rl"))
        self.checkBox_rd = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_rd.setEnabled(True)
        self.checkBox_rd.setGeometry(QtCore.QRect(30, 55, 71, 23))
        self.checkBox_rd.setObjectName(_fromUtf8("checkBox_rd"))
        self.checkBox_rdcv = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_rdcv.setEnabled(True)
        self.checkBox_rdcv.setGeometry(QtCore.QRect(30, 80, 91, 23))
        self.checkBox_rdcv.setObjectName(_fromUtf8("checkBox_rdcv"))
        self.checkBox_la = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_la.setGeometry(QtCore.QRect(30, 105, 71, 23))
        self.checkBox_la.setObjectName(_fromUtf8("checkBox_la"))
        self.checkBox_lacv = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_lacv.setGeometry(QtCore.QRect(30, 130, 91, 23))
        self.checkBox_lacv.setObjectName(_fromUtf8("checkBox_lacv"))
        self.checkBox_el = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_el.setGeometry(QtCore.QRect(30, 155, 91, 23))
        self.checkBox_el.setObjectName(_fromUtf8("checkBox_el"))
        self.checkBox_elcv = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_elcv.setGeometry(QtCore.QRect(30, 180, 111, 23))
        self.checkBox_elcv.setObjectName(_fromUtf8("checkBox_elcv"))
        self.checkBox_all = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_all.setGeometry(QtCore.QRect(30, 205, 111, 23))
        self.checkBox_all.setObjectName(_fromUtf8("checkBox_all"))
        self.label_linearRegression = QtGui.QLabel(self.groupBox_2)
        self.label_linearRegression.setGeometry(QtCore.QRect(200, 30, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_linearRegression.setFont(font)
        self.label_linearRegression.setAutoFillBackground(False)
        self.label_linearRegression.setText(_fromUtf8(""))
        self.label_linearRegression.setPixmap(QtGui.QPixmap(_fromUtf8("img/aplica.png")))
        self.label_linearRegression.setScaledContents(True)
        self.label_linearRegression.setObjectName(_fromUtf8("label_linearRegression"))
        self.label_ridge = QtGui.QLabel(self.groupBox_2)
        self.label_ridge.setGeometry(QtCore.QRect(200, 55, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_ridge.setFont(font)
        self.label_ridge.setAutoFillBackground(False)
        self.label_ridge.setText(_fromUtf8(""))
        self.label_ridge.setPixmap(QtGui.QPixmap(_fromUtf8("img/aplica.png")))
        self.label_ridge.setScaledContents(True)
        self.label_ridge.setObjectName(_fromUtf8("label_ridge"))
        self.label_ridgeCV = QtGui.QLabel(self.groupBox_2)
        self.label_ridgeCV.setGeometry(QtCore.QRect(200, 80, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_ridgeCV.setFont(font)
        self.label_ridgeCV.setAutoFillBackground(False)
        self.label_ridgeCV.setText(_fromUtf8(""))
        self.label_ridgeCV.setPixmap(QtGui.QPixmap(_fromUtf8("img/aplica.png")))
        self.label_ridgeCV.setScaledContents(True)
        self.label_ridgeCV.setObjectName(_fromUtf8("label_ridgeCV"))
        self.label_lasso = QtGui.QLabel(self.groupBox_2)
        self.label_lasso.setGeometry(QtCore.QRect(200, 105, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_lasso.setFont(font)
        self.label_lasso.setAutoFillBackground(False)
        self.label_lasso.setText(_fromUtf8(""))
        self.label_lasso.setPixmap(QtGui.QPixmap(_fromUtf8("img/aplica.png")))
        self.label_lasso.setScaledContents(True)
        self.label_lasso.setObjectName(_fromUtf8("label_lasso"))
        self.label_lassoCV = QtGui.QLabel(self.groupBox_2)
        self.label_lassoCV.setGeometry(QtCore.QRect(200, 130, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_lassoCV.setFont(font)
        self.label_lassoCV.setAutoFillBackground(False)
        self.label_lassoCV.setText(_fromUtf8(""))
        self.label_lassoCV.setPixmap(QtGui.QPixmap(_fromUtf8("img/aplica.png")))
        self.label_lassoCV.setScaledContents(True)
        self.label_lassoCV.setObjectName(_fromUtf8("label_lassoCV"))
        self.label_elasticNet = QtGui.QLabel(self.groupBox_2)
        self.label_elasticNet.setGeometry(QtCore.QRect(200, 155, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_elasticNet.setFont(font)
        self.label_elasticNet.setAutoFillBackground(False)
        self.label_elasticNet.setText(_fromUtf8(""))
        self.label_elasticNet.setPixmap(QtGui.QPixmap(_fromUtf8("img/aplica.png")))
        self.label_elasticNet.setScaledContents(True)
        self.label_elasticNet.setObjectName(_fromUtf8("label_elasticNet"))
        self.label_elasticNetCV = QtGui.QLabel(self.groupBox_2)
        self.label_elasticNetCV.setGeometry(QtCore.QRect(200, 180, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_elasticNetCV.setFont(font)
        self.label_elasticNetCV.setAutoFillBackground(False)
        self.label_elasticNetCV.setText(_fromUtf8(""))
        self.label_elasticNetCV.setPixmap(QtGui.QPixmap(_fromUtf8("img/aplica.png")))
        self.label_elasticNetCV.setScaledContents(True)
        self.label_elasticNetCV.setObjectName(_fromUtf8("label_elasticNetCV"))
        self.label_seta_1 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_1.setGeometry(QtCore.QRect(10, 30, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_1.setFont(font)
        self.label_seta_1.setAutoFillBackground(False)
        self.label_seta_1.setText(_fromUtf8(""))
        self.label_seta_1.setPixmap(QtGui.QPixmap(_fromUtf8("img/seta.png")))
        self.label_seta_1.setScaledContents(True)
        self.label_seta_1.setObjectName(_fromUtf8("label_seta_1"))
        self.label_seta_2 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_2.setGeometry(QtCore.QRect(10, 55, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_2.setFont(font)
        self.label_seta_2.setAutoFillBackground(False)
        self.label_seta_2.setText(_fromUtf8(""))
        self.label_seta_2.setPixmap(QtGui.QPixmap(_fromUtf8("img/seta.png")))
        self.label_seta_2.setScaledContents(True)
        self.label_seta_2.setObjectName(_fromUtf8("label_seta_2"))
        self.label_seta_3 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_3.setGeometry(QtCore.QRect(10, 80, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_3.setFont(font)
        self.label_seta_3.setAutoFillBackground(False)
        self.label_seta_3.setText(_fromUtf8(""))
        self.label_seta_3.setPixmap(QtGui.QPixmap(_fromUtf8("img/seta.png")))
        self.label_seta_3.setScaledContents(True)
        self.label_seta_3.setObjectName(_fromUtf8("label_seta_3"))
        self.label_seta_4 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_4.setGeometry(QtCore.QRect(10, 105, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_4.setFont(font)
        self.label_seta_4.setAutoFillBackground(False)
        self.label_seta_4.setText(_fromUtf8(""))
        self.label_seta_4.setPixmap(QtGui.QPixmap(_fromUtf8("img/seta.png")))
        self.label_seta_4.setScaledContents(True)
        self.label_seta_4.setObjectName(_fromUtf8("label_seta_4"))
        self.label_seta_5 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_5.setGeometry(QtCore.QRect(10, 130, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_5.setFont(font)
        self.label_seta_5.setAutoFillBackground(False)
        self.label_seta_5.setText(_fromUtf8(""))
        self.label_seta_5.setPixmap(QtGui.QPixmap(_fromUtf8("img/seta.png")))
        self.label_seta_5.setScaledContents(True)
        self.label_seta_5.setObjectName(_fromUtf8("label_seta_5"))
        self.label_seta_6 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_6.setGeometry(QtCore.QRect(10, 155, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_6.setFont(font)
        self.label_seta_6.setAutoFillBackground(False)
        self.label_seta_6.setText(_fromUtf8(""))
        self.label_seta_6.setPixmap(QtGui.QPixmap(_fromUtf8("img/seta.png")))
        self.label_seta_6.setScaledContents(True)
        self.label_seta_6.setObjectName(_fromUtf8("label_seta_6"))
        self.label_seta_7 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_7.setGeometry(QtCore.QRect(10, 180, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_7.setFont(font)
        self.label_seta_7.setAutoFillBackground(False)
        self.label_seta_7.setText(_fromUtf8(""))
        self.label_seta_7.setPixmap(QtGui.QPixmap(_fromUtf8("img/seta.png")))
        self.label_seta_7.setScaledContents(True)
        self.label_seta_7.setObjectName(_fromUtf8("label_seta_7"))
        self.label_all = QtGui.QLabel(self.groupBox_2)
        self.label_all.setGeometry(QtCore.QRect(200, 205, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_all.setFont(font)
        self.label_all.setAutoFillBackground(False)
        self.label_all.setText(_fromUtf8(""))
        self.label_all.setPixmap(QtGui.QPixmap(_fromUtf8("img/aplica.png")))
        self.label_all.setScaledContents(True)
        self.label_all.setObjectName(_fromUtf8("label_all"))
        self.label_seta_8 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_8.setGeometry(QtCore.QRect(10, 205, 18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_8.setFont(font)
        self.label_seta_8.setAutoFillBackground(False)
        self.label_seta_8.setText(_fromUtf8(""))
        self.label_seta_8.setPixmap(QtGui.QPixmap(_fromUtf8("img/seta.png")))
        self.label_seta_8.setScaledContents(True)
        self.label_seta_8.setObjectName(_fromUtf8("label_seta_8"))
        self.label_seta_9 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_9.setGeometry(QtCore.QRect(119, 86, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_9.setFont(font)
        self.label_seta_9.setAutoFillBackground(False)
        self.label_seta_9.setText(_fromUtf8(""))
        self.label_seta_9.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_9.setScaledContents(True)
        self.label_seta_9.setObjectName(_fromUtf8("label_seta_9"))
        self.label_seta_10 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_10.setGeometry(QtCore.QRect(130, 86, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_10.setFont(font)
        self.label_seta_10.setAutoFillBackground(False)
        self.label_seta_10.setText(_fromUtf8(""))
        self.label_seta_10.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_10.setScaledContents(True)
        self.label_seta_10.setObjectName(_fromUtf8("label_seta_10"))
        self.label_seta_11 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_11.setGeometry(QtCore.QRect(141, 86, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_11.setFont(font)
        self.label_seta_11.setAutoFillBackground(False)
        self.label_seta_11.setText(_fromUtf8(""))
        self.label_seta_11.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_11.setScaledContents(True)
        self.label_seta_11.setObjectName(_fromUtf8("label_seta_11"))
        self.label_seta_12 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_12.setGeometry(QtCore.QRect(151, 86, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_12.setFont(font)
        self.label_seta_12.setAutoFillBackground(False)
        self.label_seta_12.setText(_fromUtf8(""))
        self.label_seta_12.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_12.setScaledContents(True)
        self.label_seta_12.setObjectName(_fromUtf8("label_seta_12"))
        self.label_seta_13 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_13.setGeometry(QtCore.QRect(180, 36, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_13.setFont(font)
        self.label_seta_13.setAutoFillBackground(False)
        self.label_seta_13.setText(_fromUtf8(""))
        self.label_seta_13.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_13.setScaledContents(True)
        self.label_seta_13.setObjectName(_fromUtf8("label_seta_13"))
        self.label_seta_14 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_14.setGeometry(QtCore.QRect(100, 61, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_14.setFont(font)
        self.label_seta_14.setAutoFillBackground(False)
        self.label_seta_14.setText(_fromUtf8(""))
        self.label_seta_14.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_14.setScaledContents(True)
        self.label_seta_14.setObjectName(_fromUtf8("label_seta_14"))
        self.label_seta_15 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_15.setGeometry(QtCore.QRect(100, 112, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_15.setFont(font)
        self.label_seta_15.setAutoFillBackground(False)
        self.label_seta_15.setText(_fromUtf8(""))
        self.label_seta_15.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_15.setScaledContents(True)
        self.label_seta_15.setObjectName(_fromUtf8("label_seta_15"))
        self.label_seta_16 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_16.setGeometry(QtCore.QRect(120, 136, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_16.setFont(font)
        self.label_seta_16.setAutoFillBackground(False)
        self.label_seta_16.setText(_fromUtf8(""))
        self.label_seta_16.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_16.setScaledContents(True)
        self.label_seta_16.setObjectName(_fromUtf8("label_seta_16"))
        self.label_seta_17 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_17.setGeometry(QtCore.QRect(130, 161, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_17.setFont(font)
        self.label_seta_17.setAutoFillBackground(False)
        self.label_seta_17.setText(_fromUtf8(""))
        self.label_seta_17.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_17.setScaledContents(True)
        self.label_seta_17.setObjectName(_fromUtf8("label_seta_17"))
        self.label_seta_18 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_18.setGeometry(QtCore.QRect(149, 186, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_18.setFont(font)
        self.label_seta_18.setAutoFillBackground(False)
        self.label_seta_18.setText(_fromUtf8(""))
        self.label_seta_18.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo.png")))
        self.label_seta_18.setScaledContents(True)
        self.label_seta_18.setObjectName(_fromUtf8("label_seta_18"))
        self.label_seta_21 = QtGui.QLabel(self.groupBox_2)
        self.label_seta_21.setGeometry(QtCore.QRect(131, 136, 12, 12))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_seta_21.setFont(font)
        self.label_seta_21.setAutoFillBackground(False)
        self.label_seta_21.setText(_fromUtf8(""))
        self.label_seta_21.setPixmap(QtGui.QPixmap(_fromUtf8("img/tempo_meio.png")))
        self.label_seta_21.setScaledContents(True)
        self.label_seta_21.setObjectName(_fromUtf8("label_seta_21"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(15, 92, 870, 86))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_system = QtGui.QLabel(self.frame_3)
        self.label_system.setGeometry(QtCore.QRect(18, 50, 311, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_system.setFont(font)
        self.label_system.setObjectName(_fromUtf8("label_system"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(18, 10, 121, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(548, 10, 81, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(448, 10, 61, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_afinidade = QtGui.QLabel(self.frame_3)
        self.label_afinidade.setGeometry(QtCore.QRect(448, 50, 71, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_afinidade.setFont(font)
        self.label_afinidade.setObjectName(_fromUtf8("label_afinidade"))
        self.label_quantia = QtGui.QLabel(self.frame_3)
        self.label_quantia.setGeometry(QtCore.QRect(548, 50, 66, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_quantia.setFont(font)
        self.label_quantia.setObjectName(_fromUtf8("label_quantia"))
        self.label_tipoMedia = QtGui.QLabel(self.frame_3)
        self.label_tipoMedia.setGeometry(QtCore.QRect(340, 50, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_tipoMedia.setFont(font)
        self.label_tipoMedia.setObjectName(_fromUtf8("label_tipoMedia"))
        self.label_experimento_3 = QtGui.QLabel(self.frame_3)
        self.label_experimento_3.setGeometry(QtCore.QRect(340, 10, 71, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.label_experimento_3.sizePolicy().hasHeightForWidth())
        self.label_experimento_3.setSizePolicy(sizePolicy)
        self.label_experimento_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_experimento_3.setFont(font)
        self.label_experimento_3.setWordWrap(True)
        self.label_experimento_3.setObjectName(_fromUtf8("label_experimento_3"))
        self.label_outliers = QtGui.QLabel(self.frame_3)
        self.label_outliers.setGeometry(QtCore.QRect(800, 50, 50, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_outliers.setFont(font)
        self.label_outliers.setStyleSheet(_fromUtf8(""))
        self.label_outliers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outliers.setWordWrap(True)
        self.label_outliers.setObjectName(_fromUtf8("label_outliers"))
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(800, 11, 71, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_17 = QtGui.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(664, 9, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_estruturaInicial = QtGui.QLabel(self.frame_3)
        self.label_estruturaInicial.setGeometry(QtCore.QRect(664, 50, 61, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_estruturaInicial.setFont(font)
        self.label_estruturaInicial.setStyleSheet(_fromUtf8(""))
        self.label_estruturaInicial.setObjectName(_fromUtf8("label_estruturaInicial"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(15, 450, 870, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_tempoInicio = QtGui.QLabel(self.frame_4)
        self.label_tempoInicio.setGeometry(QtCore.QRect(103, 40, 161, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_tempoInicio.setFont(font)
        self.label_tempoInicio.setObjectName(_fromUtf8("label_tempoInicio"))
        self.label_cabecalho = QtGui.QLabel(self.frame_4)
        self.label_cabecalho.setGeometry(QtCore.QRect(20, 15, 111, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_cabecalho.setFont(font)
        self.label_cabecalho.setObjectName(_fromUtf8("label_cabecalho"))
        self.progressBar = QtGui.QProgressBar(self.frame_4)
        self.progressBar.setGeometry(QtCore.QRect(20, 73, 831, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_tempoTranscrorrido = QtGui.QLabel(self.frame_4)
        self.label_tempoTranscrorrido.setGeometry(QtCore.QRect(380, 40, 131, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_tempoTranscrorrido.setFont(font)
        self.label_tempoTranscrorrido.setObjectName(_fromUtf8("label_tempoTranscrorrido"))
        self.label_cabecalho_2 = QtGui.QLabel(self.frame_4)
        self.label_cabecalho_2.setGeometry(QtCore.QRect(20, 40, 91, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_cabecalho_2.setFont(font)
        self.label_cabecalho_2.setObjectName(_fromUtf8("label_cabecalho_2"))
        self.label_cabecalho_3 = QtGui.QLabel(self.frame_4)
        self.label_cabecalho_3.setGeometry(QtCore.QRect(280, 40, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_cabecalho_3.setFont(font)
        self.label_cabecalho_3.setObjectName(_fromUtf8("label_cabecalho_3"))
        self.label_arquivoEmProcesso = QtGui.QLabel(self.frame_4)
        self.label_arquivoEmProcesso.setGeometry(QtCore.QRect(130, 15, 531, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_arquivoEmProcesso.setFont(font)
        self.label_arquivoEmProcesso.setObjectName(_fromUtf8("label_arquivoEmProcesso"))
        self.label_cabecalho_4 = QtGui.QLabel(self.frame_4)
        self.label_cabecalho_4.setGeometry(QtCore.QRect(515, 40, 121, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_cabecalho_4.setFont(font)
        self.label_cabecalho_4.setObjectName(_fromUtf8("label_cabecalho_4"))
        self.label_tempoEstimado = QtGui.QLabel(self.frame_4)
        self.label_tempoEstimado.setGeometry(QtCore.QRect(630, 40, 151, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_tempoEstimado.setFont(font)
        self.label_tempoEstimado.setStyleSheet(_fromUtf8(""))
        self.label_tempoEstimado.setIndent(3)
        self.label_tempoEstimado.setObjectName(_fromUtf8("label_tempoEstimado"))
        self.label_cabecalho_5 = QtGui.QLabel(self.frame_4)
        self.label_cabecalho_5.setGeometry(QtCore.QRect(676, 15, 41, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_cabecalho_5.setFont(font)
        self.label_cabecalho_5.setObjectName(_fromUtf8("label_cabecalho_5"))
        self.label_seed = QtGui.QLabel(self.frame_4)
        self.label_seed.setGeometry(QtCore.QRect(720, 15, 141, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(True)
        self.label_seed.setFont(font)
        self.label_seed.setObjectName(_fromUtf8("label_seed"))
        self.label_relogio = QtGui.QLabel(self.centralwidget)
        self.label_relogio.setGeometry(QtCore.QRect(868, 437, 32, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_relogio.setFont(font)
        self.label_relogio.setAutoFillBackground(False)
        self.label_relogio.setText(_fromUtf8(""))
        self.label_relogio.setPixmap(QtGui.QPixmap(_fromUtf8("img/relogio.png")))
        self.label_relogio.setScaledContents(True)
        self.label_relogio.setObjectName(_fromUtf8("label_relogio"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 90, 65))
        self.label_27.setMaximumSize(QtCore.QSize(90, 65))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("img/TabaComLetras.png")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.frame.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.line_2.raise_()
        self.label_relogio.raise_()
        self.label_27.raise_()
        MainWindow_regressao.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_regressao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow_regressao.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_regressao)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_regressao.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_regressao)
        QtCore.QObject.connect(self.toolButton_iniciar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_regressao.iniciarRegressao)
        QtCore.QObject.connect(self.toolButton_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_regressao.sair)
        QtCore.QObject.connect(self.checkBox_all, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow_regressao.todos)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_regressao)

    def retranslateUi(self, MainWindow_regressao):
        MainWindow_regressao.setWindowTitle(_translate("MainWindow_regressao", "Do Linear Regression", None))
        MainWindow_regressao.setStatusTip(_translate("MainWindow_regressao", "Do Linear Regression", None))
        MainWindow_regressao.setWhatsThis(_translate("MainWindow_regressao", "Do Linear Regression", None))
        MainWindow_regressao.setAccessibleName(_translate("MainWindow_regressao", "regressao", None))
        MainWindow_regressao.setAccessibleDescription(_translate("MainWindow_regressao", "Do Linear Regression", None))
        self.toolButton_iniciar.setToolTip(_translate("MainWindow_regressao", "<html><head/><body><p>Start linear regression.</p></body></html>", None))
        self.toolButton_iniciar.setStatusTip(_translate("MainWindow_regressao", "Downloading", None))
        self.toolButton_iniciar.setWhatsThis(_translate("MainWindow_regressao", "Start experiment", None))
        self.toolButton_iniciar.setAccessibleName(_translate("MainWindow_regressao", "start", None))
        self.toolButton_iniciar.setText(_translate("MainWindow_regressao", "&Start", None))
        self.toolButton_exit.setToolTip(_translate("MainWindow_regressao", "Exit Experiment", None))
        self.toolButton_exit.setStatusTip(_translate("MainWindow_regressao", "Exit Experiment", None))
        self.toolButton_exit.setWhatsThis(_translate("MainWindow_regressao", "Exit", None))
        self.toolButton_exit.setAccessibleName(_translate("MainWindow_regressao", "Save", None))
        self.toolButton_exit.setText(_translate("MainWindow_regressao", "&Exit", None))
        self.comboBox_variaveis.setToolTip(_translate("MainWindow_regressao", "Number of variables to be considered in the score function", None))
        self.comboBox_variaveis.setStatusTip(_translate("MainWindow_regressao", "Number of variables to be considered in the score function", None))
        self.comboBox_variaveis.setWhatsThis(_translate("MainWindow_regressao", "Number of variables to be considered in the score function", None))
        self.comboBox_variaveis.setItemText(0, _translate("MainWindow_regressao", "2", None))
        self.comboBox_variaveis.setItemText(1, _translate("MainWindow_regressao", "3", None))
        self.comboBox_variaveis.setItemText(2, _translate("MainWindow_regressao", "4", None))
        self.comboBox_variaveis.setItemText(3, _translate("MainWindow_regressao", "5", None))
        self.comboBox_variaveis.setItemText(4, _translate("MainWindow_regressao", "6", None))
        self.comboBox_variaveis.setItemText(5, _translate("MainWindow_regressao", "7", None))
        self.comboBox_variaveis.setItemText(6, _translate("MainWindow_regressao", "8", None))
        self.comboBox_variaveis.setItemText(7, _translate("MainWindow_regressao", "9", None))
        self.comboBox_variaveis.setItemText(8, _translate("MainWindow_regressao", "10", None))
        self.label_3.setText(_translate("MainWindow_regressao", "<html><head/><body><p>Number of variables</p></body></html>", None))
        self.comboBox_dataBase.setToolTip(_translate("MainWindow_regressao", "Database where the information was obtained", None))
        self.comboBox_dataBase.setItemText(0, _translate("MainWindow_regressao", "vazio", None))
        self.label_5.setToolTip(_translate("MainWindow_regressao", "Database where the information was obtained", None))
        self.label_5.setText(_translate("MainWindow_regressao", "Data Base", None))
        self.comboBox_distance.setToolTip(_translate("MainWindow_regressao", "Distance between ligand and protein", None))
        self.comboBox_distance.setItemText(0, _translate("MainWindow_regressao", "vazio", None))
        self.label_distancia.setToolTip(_translate("MainWindow_regressao", "Distance between ligand and protein", None))
        self.label_distancia.setText(_translate("MainWindow_regressao", "Cut Distance", None))
        self.groupBox_2.setToolTip(_translate("MainWindow_regressao", "<html><head/><body><p>Methods for use in linear regression</p></body></html>", None))
        self.groupBox_2.setTitle(_translate("MainWindow_regressao", "Methods", None))
        self.checkBox_rl.setText(_translate("MainWindow_regressao", "Linear Regression", None))
        self.checkBox_rd.setText(_translate("MainWindow_regressao", "Ridge", None))
        self.checkBox_rdcv.setText(_translate("MainWindow_regressao", "RidgeCV", None))
        self.checkBox_la.setText(_translate("MainWindow_regressao", "Lasso", None))
        self.checkBox_lacv.setText(_translate("MainWindow_regressao", "LassoCV", None))
        self.checkBox_el.setText(_translate("MainWindow_regressao", "ElasticNet", None))
        self.checkBox_elcv.setText(_translate("MainWindow_regressao", "ElasticNetCV", None))
        self.checkBox_all.setText(_translate("MainWindow_regressao", "All Methods", None))
        self.label_linearRegression.setToolTip(_translate("MainWindow_regressao", "Done", None))
        self.label_ridge.setToolTip(_translate("MainWindow_regressao", "Done", None))
        self.label_ridgeCV.setToolTip(_translate("MainWindow_regressao", "Done", None))
        self.label_lasso.setToolTip(_translate("MainWindow_regressao", "Done", None))
        self.label_lassoCV.setToolTip(_translate("MainWindow_regressao", "Done", None))
        self.label_elasticNet.setToolTip(_translate("MainWindow_regressao", "Done", None))
        self.label_elasticNetCV.setToolTip(_translate("MainWindow_regressao", "Done", None))
        self.label_seta_1.setToolTip(_translate("MainWindow_regressao", "In process", None))
        self.label_seta_2.setToolTip(_translate("MainWindow_regressao", "In process", None))
        self.label_seta_3.setToolTip(_translate("MainWindow_regressao", "In process", None))
        self.label_seta_4.setToolTip(_translate("MainWindow_regressao", "In process", None))
        self.label_seta_5.setToolTip(_translate("MainWindow_regressao", "In process", None))
        self.label_seta_6.setToolTip(_translate("MainWindow_regressao", "In process", None))
        self.label_seta_7.setToolTip(_translate("MainWindow_regressao", "In process", None))
        self.label_all.setToolTip(_translate("MainWindow_regressao", "Done", None))
        self.label_seta_8.setToolTip(_translate("MainWindow_regressao", "In process", None))
        self.label_seta_9.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_10.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_11.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_12.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_13.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_14.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_15.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_16.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_17.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_18.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_seta_21.setToolTip(_translate("MainWindow_regressao", "time", None))
        self.label_system.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow_regressao", "<html><head/><body><p>Protein System Name</p></body></html>", None))
        self.label_9.setToolTip(_translate("MainWindow_regressao", "<html><head/><body><p>This is the value after the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_9.setText(_translate("MainWindow_regressao", "Number of Structures", None))
        self.label_8.setText(_translate("MainWindow_regressao", "Affinity Type", None))
        self.label_afinidade.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_quantia.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_tipoMedia.setToolTip(_translate("MainWindow_regressao", "Average Type", None))
        self.label_tipoMedia.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_experimento_3.setText(_translate("MainWindow_regressao", "Average Type", None))
        self.label_outliers.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_12.setText(_translate("MainWindow_regressao", "<html><head/><body><p>Deleted Outliers</p></body></html>", None))
        self.label_17.setToolTip(_translate("MainWindow_regressao", "<html><head/><body><p>This is the value before the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_17.setText(_translate("MainWindow_regressao", "Initial Number Structures", None))
        self.label_estruturaInicial.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_tempoInicio.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_cabecalho.setText(_translate("MainWindow_regressao", "File in process:", None))
        self.label_tempoTranscrorrido.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_cabecalho_2.setText(_translate("MainWindow_regressao", "Inital Time:", None))
        self.label_cabecalho_3.setText(_translate("MainWindow_regressao", "Elapsed time:", None))
        self.label_arquivoEmProcesso.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_cabecalho_4.setText(_translate("MainWindow_regressao", "Estimated time:", None))
        self.label_tempoEstimado.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_cabecalho_5.setToolTip(_translate("MainWindow_regressao", "<html><head/><body><p>This value is the same used in Generates File for Regression</p></body></html>", None))
        self.label_cabecalho_5.setText(_translate("MainWindow_regressao", "Seed:", None))
        self.label_seed.setToolTip(_translate("MainWindow_regressao", "<html><head/><body><p>This value is the same  used in Generates File for Regression</p></body></html>", None))
        self.label_seed.setText(_translate("MainWindow_regressao", "TextLabel", None))
        self.label_relogio.setToolTip(_translate("MainWindow_regressao", "Operation in progress. Wait please !", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow_regressao = QtGui.QMainWindow()
    ui = Ui_MainWindow_regressao()
    ui.setupUi(MainWindow_regressao)
    MainWindow_regressao.show()
    sys.exit(app.exec_())

