# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceGraficos.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowGraficos(object):
    def setupUi(self, MainWindowGraficos):
        MainWindowGraficos.setObjectName(_fromUtf8("MainWindowGraficos"))
        MainWindowGraficos.setWindowModality(QtCore.Qt.WindowModal)
        MainWindowGraficos.resize(800, 520)
        MainWindowGraficos.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindowGraficos)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(90, -1, 711, 77))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(58)
        sizePolicy.setHeightForWidth(self.horizontalLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalLayoutWidget_4.setSizePolicy(sizePolicy)
        self.horizontalLayoutWidget_4.setMinimumSize(QtCore.QSize(0, 58))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalLayoutWidget_4.setFont(font)
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_exit = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_exit.sizePolicy().hasHeightForWidth())
        self.toolButton_exit.setSizePolicy(sizePolicy)
        self.toolButton_exit.setMinimumSize(QtCore.QSize(45, 65))
        self.toolButton_exit.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.toolButton_exit.setFont(font)
        self.toolButton_exit.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_exit.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_exit.setIcon(icon)
        self.toolButton_exit.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_exit.setAutoRepeatDelay(300)
        self.toolButton_exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_exit.setAutoRaise(False)
        self.toolButton_exit.setObjectName(_fromUtf8("toolButton_exit"))
        self.horizontalLayout_2.addWidget(self.toolButton_exit)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(15, 96, 380, 350))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(18, 50, 155, 17))
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 214);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_treino = QtGui.QPushButton(self.frame_2)
        self.pushButton_treino.setGeometry(QtCore.QRect(70, 290, 61, 43))
        self.pushButton_treino.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/mostraGraficoA.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_treino.setIcon(icon1)
        self.pushButton_treino.setIconSize(QtCore.QSize(35, 40))
        self.pushButton_treino.setObjectName(_fromUtf8("pushButton_treino"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(205, 120, 155, 17))
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(0, 0, 214);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(18, 120, 155, 17))
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 214);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(205, 50, 155, 17))
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 214);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(90, 10, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(0, 0, 214);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.radioButton_reduzTreino = QtGui.QRadioButton(self.frame_2)
        self.radioButton_reduzTreino.setGeometry(QtCore.QRect(238, 300, 125, 23))
        self.radioButton_reduzTreino.setObjectName(_fromUtf8("radioButton_reduzTreino"))
        self.lineEdit_minimoXTreino = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_minimoXTreino.setGeometry(QtCore.QRect(20, 70, 113, 25))
        self.lineEdit_minimoXTreino.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_minimoXTreino.setObjectName(_fromUtf8("lineEdit_minimoXTreino"))
        self.lineEdit_maximoXTreino = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_maximoXTreino.setGeometry(QtCore.QRect(20, 140, 113, 25))
        self.lineEdit_maximoXTreino.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_maximoXTreino.setObjectName(_fromUtf8("lineEdit_maximoXTreino"))
        self.lineEdit_minimoYTreino = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_minimoYTreino.setGeometry(QtCore.QRect(207, 70, 113, 25))
        self.lineEdit_minimoYTreino.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_minimoYTreino.setObjectName(_fromUtf8("lineEdit_minimoYTreino"))
        self.lineEdit_maximoYTreino = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_maximoYTreino.setGeometry(QtCore.QRect(207, 140, 113, 25))
        self.lineEdit_maximoYTreino.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_maximoYTreino.setObjectName(_fromUtf8("lineEdit_maximoYTreino"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(407, 96, 380, 350))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(18, 50, 155, 17))
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(27, 107, 11);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(205, 50, 155, 17))
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(27, 107, 11);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_teste = QtGui.QPushButton(self.frame_3)
        self.pushButton_teste.setGeometry(QtCore.QRect(70, 290, 61, 43))
        self.pushButton_teste.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/mostraGraficoV.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_teste.setIcon(icon2)
        self.pushButton_teste.setIconSize(QtCore.QSize(35, 40))
        self.pushButton_teste.setObjectName(_fromUtf8("pushButton_teste"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(205, 120, 155, 17))
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(27, 107, 11);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(18, 120, 155, 17))
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(27, 107, 11);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(110, 10, 171, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(27, 107, 11);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.radioButton_reduzTeste = QtGui.QRadioButton(self.frame_3)
        self.radioButton_reduzTeste.setGeometry(QtCore.QRect(238, 300, 125, 23))
        self.radioButton_reduzTeste.setObjectName(_fromUtf8("radioButton_reduzTeste"))
        self.lineEdit_minimoXTeste = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_minimoXTeste.setGeometry(QtCore.QRect(20, 70, 113, 25))
        self.lineEdit_minimoXTeste.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_minimoXTeste.setObjectName(_fromUtf8("lineEdit_minimoXTeste"))
        self.lineEdit_minimoYTeste = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_minimoYTeste.setGeometry(QtCore.QRect(207, 70, 113, 25))
        self.lineEdit_minimoYTeste.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_minimoYTeste.setObjectName(_fromUtf8("lineEdit_minimoYTeste"))
        self.lineEdit_maximoXTeste = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_maximoXTeste.setGeometry(QtCore.QRect(20, 140, 113, 25))
        self.lineEdit_maximoXTeste.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_maximoXTeste.setObjectName(_fromUtf8("lineEdit_maximoXTeste"))
        self.lineEdit_maximoYTeste = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_maximoYTeste.setGeometry(QtCore.QRect(207, 140, 113, 25))
        self.lineEdit_maximoYTeste.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_maximoYTeste.setObjectName(_fromUtf8("lineEdit_maximoYTeste"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 800, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtGui.QFrame.Raised)
        self.line_2.setLineWidth(4)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 450, 781, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 251, 202);"))
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_11 = QtGui.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 3, 741, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setToolTip(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 90, 65))
        self.label_27.setMaximumSize(QtCore.QSize(90, 65))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("img/TabaComLetras.png")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        MainWindowGraficos.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowGraficos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindowGraficos.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowGraficos)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowGraficos.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowGraficos)
        QtCore.QObject.connect(self.toolButton_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowGraficos.close)
        QtCore.QObject.connect(self.pushButton_treino, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowGraficos.geraGraficoTreino)
        QtCore.QObject.connect(self.pushButton_teste, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowGraficos.geraGraficoTeste)
        QtCore.QObject.connect(self.radioButton_reduzTreino, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowGraficos.habilitaReducaoTreino)
        QtCore.QObject.connect(self.radioButton_reduzTeste, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindowGraficos.habilitaReducaoTeste)
        QtCore.QMetaObject.connectSlotsByName(MainWindowGraficos)

    def retranslateUi(self, MainWindowGraficos):
        MainWindowGraficos.setWindowTitle(_translate("MainWindowGraficos", "Generate Plots", None))
        self.toolButton_exit.setToolTip(_translate("MainWindowGraficos", "Exit Experiment", None))
        self.toolButton_exit.setStatusTip(_translate("MainWindowGraficos", "Exit Experiment", None))
        self.toolButton_exit.setWhatsThis(_translate("MainWindowGraficos", "Exit", None))
        self.toolButton_exit.setAccessibleName(_translate("MainWindowGraficos", "Exit", None))
        self.toolButton_exit.setText(_translate("MainWindowGraficos", "&Exit", None))
        self.label.setText(_translate("MainWindowGraficos", "Minimum value X-axis", None))
        self.pushButton_treino.setToolTip(_translate("MainWindowGraficos", "generate Training Chart", None))
        self.pushButton_treino.setStatusTip(_translate("MainWindowGraficos", "generate Training Chart", None))
        self.pushButton_treino.setWhatsThis(_translate("MainWindowGraficos", "generate Training Chart", None))
        self.label_4.setText(_translate("MainWindowGraficos", "Maximum value Y-axis", None))
        self.label_3.setText(_translate("MainWindowGraficos", "Maximum value X-axis", None))
        self.label_2.setText(_translate("MainWindowGraficos", "Minimum value Y-axis", None))
        self.label_9.setText(_translate("MainWindowGraficos", "Show Training Plot", None))
        self.radioButton_reduzTreino.setText(_translate("MainWindowGraficos", "Reduce Range", None))
        self.lineEdit_minimoXTreino.setText(_translate("MainWindowGraficos", "0", None))
        self.lineEdit_maximoXTreino.setText(_translate("MainWindowGraficos", "0", None))
        self.lineEdit_minimoYTreino.setText(_translate("MainWindowGraficos", "0", None))
        self.lineEdit_maximoYTreino.setText(_translate("MainWindowGraficos", "0", None))
        self.label_5.setText(_translate("MainWindowGraficos", "Minimum value X-axis", None))
        self.label_6.setText(_translate("MainWindowGraficos", "Minimum value Y-axis", None))
        self.pushButton_teste.setToolTip(_translate("MainWindowGraficos", "generate Teste Chart", None))
        self.pushButton_teste.setStatusTip(_translate("MainWindowGraficos", "generate Teste Chart", None))
        self.pushButton_teste.setWhatsThis(_translate("MainWindowGraficos", "generate Teste Chart", None))
        self.label_8.setText(_translate("MainWindowGraficos", "Maximum value Y-axis", None))
        self.label_7.setText(_translate("MainWindowGraficos", "Maximum value X-axis", None))
        self.label_10.setText(_translate("MainWindowGraficos", "Show Test Plot", None))
        self.radioButton_reduzTeste.setText(_translate("MainWindowGraficos", "Reduce Range", None))
        self.lineEdit_minimoXTeste.setText(_translate("MainWindowGraficos", "0", None))
        self.lineEdit_minimoYTeste.setText(_translate("MainWindowGraficos", "0", None))
        self.lineEdit_maximoXTeste.setText(_translate("MainWindowGraficos", "0", None))
        self.lineEdit_maximoYTeste.setText(_translate("MainWindowGraficos", "0", None))
        self.label_11.setText(_translate("MainWindowGraficos", "<html><head/><body><p><span style=\" font-weight:600;\">Note:</span> You can reduce the ranges of x-axis and y-axis values or keep the full range.</p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindowGraficos = QtGui.QMainWindow()
    ui = Ui_MainWindowGraficos()
    ui.setupUi(MainWindowGraficos)
    MainWindowGraficos.show()
    sys.exit(app.exec_())

