# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceGestaoExperimentos.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_manageFiles(object):
    def setupUi(self, MainWindow_manageFiles):
        MainWindow_manageFiles.setObjectName(_fromUtf8("MainWindow_manageFiles"))
        MainWindow_manageFiles.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow_manageFiles.resize(950, 600)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        MainWindow_manageFiles.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/beagle3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_manageFiles.setWindowIcon(icon)
        MainWindow_manageFiles.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow_manageFiles)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(90, 0, 881, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.horizontalLayoutWidget_4.setFont(font)
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_exit = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        self.toolButton_exit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.toolButton_exit.sizePolicy().hasHeightForWidth())
        self.toolButton_exit.setSizePolicy(sizePolicy)
        self.toolButton_exit.setMinimumSize(QtCore.QSize(52, 63))
        self.toolButton_exit.setMaximumSize(QtCore.QSize(80, 65))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(11)
        font.setItalic(False)
        self.toolButton_exit.setFont(font)
        self.toolButton_exit.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_exit.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_exit.setIcon(icon1)
        self.toolButton_exit.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_exit.setAutoRepeatDelay(300)
        self.toolButton_exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_exit.setAutoRaise(False)
        self.toolButton_exit.setObjectName(_fromUtf8("toolButton_exit"))
        self.horizontalLayout_2.addWidget(self.toolButton_exit)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(15, 303, 440, 251))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(110, 44, 241, 16))
        self.label_4.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_experimento = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_experimento.setGeometry(QtCore.QRect(100, 60, 333, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.lineEdit_experimento.setFont(font)
        self.lineEdit_experimento.setAcceptDrops(True)
        self.lineEdit_experimento.setObjectName(_fromUtf8("lineEdit_experimento"))
        self.comboBox_arquivos = QtGui.QComboBox(self.frame_3)
        self.comboBox_arquivos.setGeometry(QtCore.QRect(100, 114, 333, 25))
        self.comboBox_arquivos.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_arquivos.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.comboBox_arquivos.setFont(font)
        self.comboBox_arquivos.setObjectName(_fromUtf8("comboBox_arquivos"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(110, 98, 200, 16))
        self.label_8.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(110, 152, 200, 16))
        self.label_10.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox_deletaArquivos = QtGui.QComboBox(self.frame_3)
        self.comboBox_deletaArquivos.setGeometry(QtCore.QRect(100, 168, 333, 25))
        self.comboBox_deletaArquivos.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_deletaArquivos.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.comboBox_deletaArquivos.setFont(font)
        self.comboBox_deletaArquivos.setObjectName(_fromUtf8("comboBox_deletaArquivos"))
        self.pushButton_salvar = QtGui.QPushButton(self.frame_3)
        self.pushButton_salvar.setGeometry(QtCore.QRect(10, 57, 85, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/salvar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_salvar.setIcon(icon2)
        self.pushButton_salvar.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_salvar.setObjectName(_fromUtf8("pushButton_salvar"))
        self.pushButton_recuperar = QtGui.QPushButton(self.frame_3)
        self.pushButton_recuperar.setGeometry(QtCore.QRect(10, 111, 85, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/recupera.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_recuperar.setIcon(icon3)
        self.pushButton_recuperar.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_recuperar.setObjectName(_fromUtf8("pushButton_recuperar"))
        self.pushButton_apagar = QtGui.QPushButton(self.frame_3)
        self.pushButton_apagar.setGeometry(QtCore.QRect(10, 165, 85, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/deletar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_apagar.setIcon(icon4)
        self.pushButton_apagar.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_apagar.setObjectName(_fromUtf8("pushButton_apagar"))
        self.pushButton_exporta = QtGui.QPushButton(self.frame_3)
        self.pushButton_exporta.setGeometry(QtCore.QRect(10, 210, 205, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exporta.setIcon(icon5)
        self.pushButton_exporta.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_exporta.setObjectName(_fromUtf8("pushButton_exporta"))
        self.pushButton_importa = QtGui.QPushButton(self.frame_3)
        self.pushButton_importa.setGeometry(QtCore.QRect(229, 210, 205, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_importa.setIcon(icon6)
        self.pushButton_importa.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_importa.setObjectName(_fromUtf8("pushButton_importa"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 8, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(15, 94, 920, 201))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(24, 2, 271, 25))
        self.label_9.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_experimento = QtGui.QLabel(self.frame_5)
        self.label_experimento.setGeometry(QtCore.QRect(294, 11, 461, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_experimento.setFont(font)
        self.label_experimento.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_experimento.setObjectName(_fromUtf8("label_experimento"))
        self.label_editPdb_3 = QtGui.QLabel(self.frame_5)
        self.label_editPdb_3.setGeometry(QtCore.QRect(16, 123, 900, 25))
        self.label_editPdb_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_editPdb_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_editPdb_3.setFont(font)
        self.label_editPdb_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_editPdb_3.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_editPdb_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_editPdb_3.setIndent(10)
        self.label_editPdb_3.setObjectName(_fromUtf8("label_editPdb_3"))
        self.label_comentarios = QtGui.QLabel(self.frame_5)
        self.label_comentarios.setGeometry(QtCore.QRect(16, 148, 900, 45))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_comentarios.sizePolicy().hasHeightForWidth())
        self.label_comentarios.setSizePolicy(sizePolicy)
        self.label_comentarios.setMinimumSize(QtCore.QSize(0, 20))
        self.label_comentarios.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label_comentarios.setFont(font)
        self.label_comentarios.setAutoFillBackground(False)
        self.label_comentarios.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_comentarios.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_comentarios.setWordWrap(True)
        self.label_comentarios.setIndent(10)
        self.label_comentarios.setObjectName(_fromUtf8("label_comentarios"))
        self.label_outliers = QtGui.QLabel(self.frame_5)
        self.label_outliers.setGeometry(QtCore.QRect(362, 102, 173, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_outliers.sizePolicy().hasHeightForWidth())
        self.label_outliers.setSizePolicy(sizePolicy)
        self.label_outliers.setMinimumSize(QtCore.QSize(0, 20))
        self.label_outliers.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label_outliers.setFont(font)
        self.label_outliers.setAutoFillBackground(False)
        self.label_outliers.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_outliers.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_outliers.setWordWrap(True)
        self.label_outliers.setIndent(10)
        self.label_outliers.setObjectName(_fromUtf8("label_outliers"))
        self.label_deleteLigand = QtGui.QLabel(self.frame_5)
        self.label_deleteLigand.setGeometry(QtCore.QRect(535, 102, 173, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_deleteLigand.sizePolicy().hasHeightForWidth())
        self.label_deleteLigand.setSizePolicy(sizePolicy)
        self.label_deleteLigand.setMinimumSize(QtCore.QSize(0, 20))
        self.label_deleteLigand.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label_deleteLigand.setFont(font)
        self.label_deleteLigand.setAutoFillBackground(False)
        self.label_deleteLigand.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_deleteLigand.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_deleteLigand.setWordWrap(True)
        self.label_deleteLigand.setIndent(10)
        self.label_deleteLigand.setObjectName(_fromUtf8("label_deleteLigand"))
        self.label_editPdb_2 = QtGui.QLabel(self.frame_5)
        self.label_editPdb_2.setGeometry(QtCore.QRect(16, 30, 731, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_editPdb_2.sizePolicy().hasHeightForWidth())
        self.label_editPdb_2.setSizePolicy(sizePolicy)
        self.label_editPdb_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_editPdb_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_editPdb_2.setFont(font)
        self.label_editPdb_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_editPdb_2.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_editPdb_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_editPdb_2.setWordWrap(True)
        self.label_editPdb_2.setIndent(10)
        self.label_editPdb_2.setObjectName(_fromUtf8("label_editPdb_2"))
        self.label_estruturaInicial = QtGui.QLabel(self.frame_5)
        self.label_estruturaInicial.setGeometry(QtCore.QRect(16, 102, 173, 22))
        self.label_estruturaInicial.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label_estruturaInicial.setFont(font)
        self.label_estruturaInicial.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_estruturaInicial.setIndent(10)
        self.label_estruturaInicial.setObjectName(_fromUtf8("label_estruturaInicial"))
        self.label_12 = QtGui.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(189, 77, 173, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setIndent(10)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_16 = QtGui.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(535, 77, 173, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 25))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setIndent(10)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_15 = QtGui.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(16, 77, 173, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_15.setWordWrap(True)
        self.label_15.setIndent(10)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_14 = QtGui.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(362, 77, 173, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 25))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setIndent(10)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_quantia = QtGui.QLabel(self.frame_5)
        self.label_quantia.setGeometry(QtCore.QRect(189, 102, 173, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_quantia.sizePolicy().hasHeightForWidth())
        self.label_quantia.setSizePolicy(sizePolicy)
        self.label_quantia.setMinimumSize(QtCore.QSize(0, 20))
        self.label_quantia.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label_quantia.setFont(font)
        self.label_quantia.setAutoFillBackground(False)
        self.label_quantia.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_quantia.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_quantia.setWordWrap(True)
        self.label_quantia.setIndent(10)
        self.label_quantia.setObjectName(_fromUtf8("label_quantia"))
        self.label_descricao = QtGui.QLabel(self.frame_5)
        self.label_descricao.setGeometry(QtCore.QRect(16, 55, 731, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_descricao.sizePolicy().hasHeightForWidth())
        self.label_descricao.setSizePolicy(sizePolicy)
        self.label_descricao.setMinimumSize(QtCore.QSize(0, 20))
        self.label_descricao.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label_descricao.setFont(font)
        self.label_descricao.setAutoFillBackground(False)
        self.label_descricao.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_descricao.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_descricao.setWordWrap(False)
        self.label_descricao.setIndent(10)
        self.label_descricao.setObjectName(_fromUtf8("label_descricao"))
        self.label_editPdb_4 = QtGui.QLabel(self.frame_5)
        self.label_editPdb_4.setGeometry(QtCore.QRect(745, 30, 170, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_editPdb_4.sizePolicy().hasHeightForWidth())
        self.label_editPdb_4.setSizePolicy(sizePolicy)
        self.label_editPdb_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_editPdb_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_editPdb_4.setFont(font)
        self.label_editPdb_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_editPdb_4.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_editPdb_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_editPdb_4.setWordWrap(True)
        self.label_editPdb_4.setIndent(10)
        self.label_editPdb_4.setObjectName(_fromUtf8("label_editPdb_4"))
        self.label_afinidade = QtGui.QLabel(self.frame_5)
        self.label_afinidade.setGeometry(QtCore.QRect(745, 55, 170, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_afinidade.sizePolicy().hasHeightForWidth())
        self.label_afinidade.setSizePolicy(sizePolicy)
        self.label_afinidade.setMinimumSize(QtCore.QSize(0, 20))
        self.label_afinidade.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label_afinidade.setFont(font)
        self.label_afinidade.setAutoFillBackground(False)
        self.label_afinidade.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_afinidade.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_afinidade.setWordWrap(False)
        self.label_afinidade.setIndent(10)
        self.label_afinidade.setObjectName(_fromUtf8("label_afinidade"))
        self.label_17 = QtGui.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(708, 77, 208, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 25))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet(_fromUtf8("background-color: rgb(193, 193, 193);"))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setIndent(10)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_data = QtGui.QLabel(self.frame_5)
        self.label_data.setGeometry(QtCore.QRect(708, 102, 208, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data.sizePolicy().hasHeightForWidth())
        self.label_data.setSizePolicy(sizePolicy)
        self.label_data.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        font.setItalic(False)
        self.label_data.setFont(font)
        self.label_data.setAutoFillBackground(False)
        self.label_data.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.label_data.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_data.setWordWrap(True)
        self.label_data.setIndent(10)
        self.label_data.setObjectName(_fromUtf8("label_data"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 950, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtGui.QFrame.Raised)
        self.line_2.setLineWidth(4)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.checkBox_atalho = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_atalho.setGeometry(QtCore.QRect(12, 550, 251, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_atalho.setFont(font)
        self.checkBox_atalho.setChecked(True)
        self.checkBox_atalho.setObjectName(_fromUtf8("checkBox_atalho"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(467, 303, 468, 251))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.toolButton_recuperar_6 = QtGui.QToolButton(self.frame_4)
        self.toolButton_recuperar_6.setGeometry(QtCore.QRect(670, 30, 52, 56))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(52)
        sizePolicy.setHeightForWidth(self.toolButton_recuperar_6.sizePolicy().hasHeightForWidth())
        self.toolButton_recuperar_6.setSizePolicy(sizePolicy)
        self.toolButton_recuperar_6.setMinimumSize(QtCore.QSize(52, 50))
        self.toolButton_recuperar_6.setMaximumSize(QtCore.QSize(52, 56))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.toolButton_recuperar_6.setFont(font)
        self.toolButton_recuperar_6.setAccessibleDescription(_fromUtf8(""))
        self.toolButton_recuperar_6.setAutoFillBackground(False)
        self.toolButton_recuperar_6.setIcon(icon4)
        self.toolButton_recuperar_6.setIconSize(QtCore.QSize(28, 28))
        self.toolButton_recuperar_6.setAutoRepeatDelay(300)
        self.toolButton_recuperar_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_recuperar_6.setAutoRaise(False)
        self.toolButton_recuperar_6.setObjectName(_fromUtf8("toolButton_recuperar_6"))
        self.pushButton = QtGui.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(170, 210, 111, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/borracha.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 44, 371, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_toExperiment = QtGui.QLabel(self.frame_4)
        self.label_toExperiment.setGeometry(QtCore.QRect(10, 61, 421, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_toExperiment.setFont(font)
        self.label_toExperiment.setStyleSheet(_fromUtf8("color: rgb(32, 74, 135);"))
        self.label_toExperiment.setObjectName(_fromUtf8("label_toExperiment"))
        self.groupBox = QtGui.QGroupBox(self.frame_4)
        self.groupBox.setGeometry(QtCore.QRect(3, 75, 460, 131))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 98, 451, 23))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 46, 321, 23))
        self.radioButton_2.setStatusTip(_fromUtf8(""))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 72, 411, 23))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_1 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_1.setGeometry(QtCore.QRect(10, 20, 321, 23))
        self.radioButton_1.setStatusTip(_fromUtf8(""))
        self.radioButton_1.setObjectName(_fromUtf8("radioButton_1"))
        self.label_3 = QtGui.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 8, 231, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_relogio = QtGui.QLabel(self.centralwidget)
        self.label_relogio.setGeometry(QtCore.QRect(438, 290, 32, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_relogio.setFont(font)
        self.label_relogio.setAutoFillBackground(False)
        self.label_relogio.setText(_fromUtf8(""))
        self.label_relogio.setPixmap(QtGui.QPixmap(_fromUtf8("img/relogio.png")))
        self.label_relogio.setScaledContents(True)
        self.label_relogio.setObjectName(_fromUtf8("label_relogio"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 90, 59))
        self.label_27.setMaximumSize(QtCore.QSize(90, 65))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("img/TabaComLetras.png")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.frame_3.raise_()
        self.frame_5.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.line_2.raise_()
        self.checkBox_atalho.raise_()
        self.frame_4.raise_()
        self.label_relogio.raise_()
        self.label_27.raise_()
        MainWindow_manageFiles.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_manageFiles)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow_manageFiles.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_manageFiles)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_manageFiles.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_manageFiles)
        QtCore.QObject.connect(self.toolButton_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_manageFiles.sair)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_manageFiles.apagaArquivos)
        QtCore.QObject.connect(self.pushButton_salvar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_manageFiles.salvarExperimentos)
        QtCore.QObject.connect(self.pushButton_recuperar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_manageFiles.recuperarExperimentos)
        QtCore.QObject.connect(self.checkBox_atalho, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_manageFiles.criaAtalho)
        QtCore.QObject.connect(self.pushButton_exporta, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_manageFiles.exportaArquivo)
        QtCore.QObject.connect(self.pushButton_importa, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_manageFiles.importaArquivo)
        QtCore.QObject.connect(self.pushButton_apagar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_manageFiles.deletar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_manageFiles)

    def retranslateUi(self, MainWindow_manageFiles):
        MainWindow_manageFiles.setWindowTitle(_translate("MainWindow_manageFiles", "Manage Experiments", None))
        self.toolButton_exit.setToolTip(_translate("MainWindow_manageFiles", "Exit Experiment", None))
        self.toolButton_exit.setStatusTip(_translate("MainWindow_manageFiles", "Exit Experiment", None))
        self.toolButton_exit.setWhatsThis(_translate("MainWindow_manageFiles", "Exit", None))
        self.toolButton_exit.setAccessibleName(_translate("MainWindow_manageFiles", "Save", None))
        self.toolButton_exit.setText(_translate("MainWindow_manageFiles", "&Exit", None))
        self.label_4.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>Enter the number of variables whished to equation</p></body></html>", None))
        self.label_4.setText(_translate("MainWindow_manageFiles", "Name of Experiment Set to Save", None))
        self.comboBox_arquivos.setToolTip(_translate("MainWindow_manageFiles", "choose the file to use", None))
        self.label_8.setToolTip(_translate("MainWindow_manageFiles", "choose the file to use", None))
        self.label_8.setText(_translate("MainWindow_manageFiles", "Experiment to Recover", None))
        self.label_10.setToolTip(_translate("MainWindow_manageFiles", "choose the file to use", None))
        self.label_10.setText(_translate("MainWindow_manageFiles", "Experiment to Delete", None))
        self.comboBox_deletaArquivos.setToolTip(_translate("MainWindow_manageFiles", "choose the file to use", None))
        self.pushButton_salvar.setToolTip(_translate("MainWindow_manageFiles", "Save experiment", None))
        self.pushButton_salvar.setStatusTip(_translate("MainWindow_manageFiles", "Save experiment", None))
        self.pushButton_salvar.setWhatsThis(_translate("MainWindow_manageFiles", "Save experiment", None))
        self.pushButton_salvar.setText(_translate("MainWindow_manageFiles", "&Save", None))
        self.pushButton_recuperar.setToolTip(_translate("MainWindow_manageFiles", "Recover experiment", None))
        self.pushButton_recuperar.setStatusTip(_translate("MainWindow_manageFiles", "Recover experiment", None))
        self.pushButton_recuperar.setWhatsThis(_translate("MainWindow_manageFiles", "Recover experiment", None))
        self.pushButton_recuperar.setText(_translate("MainWindow_manageFiles", "&Recover", None))
        self.pushButton_apagar.setToolTip(_translate("MainWindow_manageFiles", "Delete a saved experiment.\n"
"To delete the current experiment, create a New Experiment in PDB(Handle PDB Structure).", None))
        self.pushButton_apagar.setStatusTip(_translate("MainWindow_manageFiles", "Delete a saved experiment. To delete the current experiment, create a New Experiment in PDB(Handle PDB Structure).", None))
        self.pushButton_apagar.setWhatsThis(_translate("MainWindow_manageFiles", "Delete a saved experiment.\n"
"To delete the current experiment, create a New Experiment in PDB(Handle PDB Structure).", None))
        self.pushButton_apagar.setText(_translate("MainWindow_manageFiles", "&Delete", None))
        self.pushButton_exporta.setToolTip(_translate("MainWindow_manageFiles", "Exports an experiment into a compressed file", None))
        self.pushButton_exporta.setStatusTip(_translate("MainWindow_manageFiles", "Exports an experiment into a compressed file", None))
        self.pushButton_exporta.setWhatsThis(_translate("MainWindow_manageFiles", "Exports an experiment into a compressed file", None))
        self.pushButton_exporta.setText(_translate("MainWindow_manageFiles", "&Export Zipped Experiment", None))
        self.pushButton_importa.setToolTip(_translate("MainWindow_manageFiles", "Import a compressed file experiment", None))
        self.pushButton_importa.setStatusTip(_translate("MainWindow_manageFiles", "Import a compressed file experiment", None))
        self.pushButton_importa.setWhatsThis(_translate("MainWindow_manageFiles", "Import a compressed file experiment", None))
        self.pushButton_importa.setText(_translate("MainWindow_manageFiles", "&Import  Zipped Experiment", None))
        self.label_2.setText(_translate("MainWindow_manageFiles", "Manange Files", None))
        self.label_9.setToolTip(_translate("MainWindow_manageFiles", "choose the file to use", None))
        self.label_9.setText(_translate("MainWindow_manageFiles", "<html><head/><body><p>Last Run Information for Experiment:</p></body></html>", None))
        self.label_experimento.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.label_editPdb_3.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>Post your comments about the current experiment here.</p></body></html>", None))
        self.label_editPdb_3.setText(_translate("MainWindow_manageFiles", "<html><head/><body><p>Comments</p></body></html>", None))
        self.label_comentarios.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.label_outliers.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>If &quot;yes&quot;, the outliers have already been deleted</p></body></html>", None))
        self.label_outliers.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.label_deleteLigand.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>Repetead Ligand Eliminated</p></body></html>", None))
        self.label_deleteLigand.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.label_editPdb_2.setText(_translate("MainWindow_manageFiles", "<html><head/><body><p>Protein System Name</p></body></html>", None))
        self.label_estruturaInicial.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.label_12.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>This is the value after the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_12.setText(_translate("MainWindow_manageFiles", "Number of Structures", None))
        self.label_16.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>Repetead Ligand Were Eliminated</p></body></html>", None))
        self.label_16.setText(_translate("MainWindow_manageFiles", "<html><head/><body><p>Repetead Ligand Eliminated</p></body></html>", None))
        self.label_15.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>This is the value before the outliers and repeated ligands are deleted.</p></body></html>", None))
        self.label_15.setText(_translate("MainWindow_manageFiles", "Initial Number Structures", None))
        self.label_14.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>If &quot;yes&quot;, the outliers have already been deleted.</p><p>You can exclude the outliers for this experiment only once  time.</p></body></html>", None))
        self.label_14.setText(_translate("MainWindow_manageFiles", "Deleted Outliers", None))
        self.label_quantia.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.label_descricao.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.label_editPdb_4.setText(_translate("MainWindow_manageFiles", "<html><head/><body><p>Affinity Type</p></body></html>", None))
        self.label_afinidade.setText(_translate("MainWindow_manageFiles", "<html><head/><body><p>Affinity Type</p></body></html>", None))
        self.label_17.setToolTip(_translate("MainWindow_manageFiles", "Date the experiment was last saved", None))
        self.label_17.setStatusTip(_translate("MainWindow_manageFiles", "Date the experiment was last saved", None))
        self.label_17.setWhatsThis(_translate("MainWindow_manageFiles", "Date the experiment was last saved", None))
        self.label_17.setText(_translate("MainWindow_manageFiles", "<html><head/><body><p>Recorded In</p></body></html>", None))
        self.label_data.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.checkBox_atalho.setToolTip(_translate("MainWindow_manageFiles", "If checked it will create a shortcut on the desktop", None))
        self.checkBox_atalho.setText(_translate("MainWindow_manageFiles", "Create a shortcut on the desktop", None))
        self.toolButton_recuperar_6.setToolTip(_translate("MainWindow_manageFiles", "<html><head/><body><p>Delete a saved experiment.</p><p>To delete the current experiment, create a New Experiment in PDB(Handle PDB Structure).</p></body></html>", None))
        self.toolButton_recuperar_6.setStatusTip(_translate("MainWindow_manageFiles", "Delete a saved experiment", None))
        self.toolButton_recuperar_6.setWhatsThis(_translate("MainWindow_manageFiles", "Delete a saved experiment", None))
        self.toolButton_recuperar_6.setAccessibleName(_translate("MainWindow_manageFiles", "Delete a saved experiment", None))
        self.toolButton_recuperar_6.setText(_translate("MainWindow_manageFiles", "&Delete", None))
        self.pushButton.setToolTip(_translate("MainWindow_manageFiles", "Delete Files Generated in the Experiment", None))
        self.pushButton.setStatusTip(_translate("MainWindow_manageFiles", "Delete Files Generated in the Experiment", None))
        self.pushButton.setWhatsThis(_translate("MainWindow_manageFiles", "Delete Files Generated in the Experiment", None))
        self.pushButton.setText(_translate("MainWindow_manageFiles", "&Erase Files", None))
        self.label.setText(_translate("MainWindow_manageFiles", "Check the file types you want to clean to experiment:", None))
        self.label_toExperiment.setText(_translate("MainWindow_manageFiles", "TextLabel", None))
        self.radioButton_4.setToolTip(_translate("MainWindow_manageFiles", "This will delete the PDB files downloaded in \"PDB\", the files generated in \"Make Files\", \n"
"the linear regression files generated in \"Regression\" and also the models generated\n"
"in the \"Correlation\" option of the main menu.", None))
        self.radioButton_4.setText(_translate("MainWindow_manageFiles", "PDBs, Files for Regression, Linear Regression Files and Models", None))
        self.radioButton_2.setToolTip(_translate("MainWindow_manageFiles", "This will delete the linear regression files generated in \"Regression\"\n"
"and also the models generated in the \"Correlation\" option of the main menu.", None))
        self.radioButton_2.setText(_translate("MainWindow_manageFiles", "Linear Regression Files and Models", None))
        self.radioButton_3.setToolTip(_translate("MainWindow_manageFiles", "This will delete the files generated in \"Make Files\", the linear regression files \n"
"generated in \"Regression\" and also the models generated in the \"Correlation\"\n"
"option of the main menu.", None))
        self.radioButton_3.setText(_translate("MainWindow_manageFiles", "Files for Regression, Linear Regression Files and Models", None))
        self.radioButton_1.setToolTip(_translate("MainWindow_manageFiles", "This will delete only the models generated in the\n"
" \"Correlation\" option of the main menu.", None))
        self.radioButton_1.setText(_translate("MainWindow_manageFiles", "Models", None))
        self.label_3.setText(_translate("MainWindow_manageFiles", "Delete Part of This Experiment", None))
        self.label_relogio.setToolTip(_translate("MainWindow_manageFiles", "Operation in progress. Wait please !", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow_manageFiles = QtGui.QMainWindow()
    ui = Ui_MainWindow_manageFiles()
    ui.setupUi(MainWindow_manageFiles)
    MainWindow_manageFiles.show()
    sys.exit(app.exec_())

